-- src/ion7/core/ffi/ggml/alloc.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: ggml-alloc.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  struct ggml_tallocr ggml_tallocr_new(ggml_backend_buffer_t buffer);
  enum ggml_status ggml_tallocr_alloc(struct ggml_tallocr * talloc, struct ggml_tensor * tensor);
  ggml_gallocr_t ggml_gallocr_new(ggml_backend_buffer_type_t buft);
  ggml_gallocr_t ggml_gallocr_new_n(ggml_backend_buffer_type_t * bufts, int n_bufs);
  void ggml_gallocr_free(ggml_gallocr_t galloc);
  bool ggml_gallocr_reserve(ggml_gallocr_t galloc, struct ggml_cgraph * graph);
  void ggml_gallocr_reserve_n_size(ggml_gallocr_t galloc, struct ggml_cgraph * graph, const int * node_buffer_ids, const int * leaf_buffer_ids, size_t * sizes);
  bool ggml_gallocr_reserve_n(ggml_gallocr_t galloc, struct ggml_cgraph * graph, const int * node_buffer_ids, const int * leaf_buffer_ids);
  bool ggml_gallocr_alloc_graph(ggml_gallocr_t galloc, struct ggml_cgraph * graph);
  size_t ggml_gallocr_get_buffer_size(ggml_gallocr_t galloc, int buffer_id);
]]
local loader = require "ion7.core.ffi.loader"
return loader.ggml
