-- src/ion7/core/ffi/ggml/blas.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: ggml-blas.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  ggml_backend_t ggml_backend_blas_init(void);
  void ggml_backend_blas_set_n_threads(ggml_backend_t backend_blas, int n_threads);
  ggml_backend_reg_t ggml_backend_blas_reg(void);
]]
local loader = require "ion7.core.ffi.loader"
return loader.ggml
