-- src/ion7/core/ffi/ggml/context.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: ggml.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  struct ggml_context * ggml_init(struct ggml_init_params params);
  void ggml_free(struct ggml_context * ctx);
  size_t ggml_used_mem(const struct ggml_context * ctx);
]]
local loader = require "ion7.core.ffi.loader"
return loader.ggml
