-- src/ion7/core/ffi/ggml/cpu.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: ggml-backend.h, ggml-cpu.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  int ggml_cpu_has_sse3(void);
  int ggml_cpu_has_ssse3(void);
  int ggml_cpu_has_avx(void);
  int ggml_cpu_has_avx_vnni(void);
  int ggml_cpu_has_avx2(void);
  int ggml_cpu_has_bmi2(void);
  int ggml_cpu_has_f16c(void);
  int ggml_cpu_has_fma(void);
  int ggml_cpu_has_avx512(void);
  int ggml_cpu_has_avx512_vbmi(void);
  int ggml_cpu_has_avx512_vnni(void);
  int ggml_cpu_has_avx512_bf16(void);
  int ggml_cpu_has_amx_int8(void);
  int ggml_cpu_has_neon(void);
  int ggml_cpu_has_arm_fma(void);
  int ggml_cpu_has_fp16_va(void);
  int ggml_cpu_has_dotprod(void);
  int ggml_cpu_has_matmul_int8(void);
  int ggml_cpu_has_sve(void);
  int ggml_cpu_get_sve_cnt(void);
  int ggml_cpu_has_sme(void);
  int ggml_cpu_has_riscv_v(void);
  int ggml_cpu_get_rvv_vlen(void);
  int ggml_cpu_has_vsx(void);
  int ggml_cpu_has_vxe(void);
  int ggml_cpu_has_wasm_simd(void);
  int ggml_cpu_has_llamafile(void);
  void ggml_cpu_init(void);
  ggml_backend_t ggml_backend_cpu_init(void);
  void ggml_backend_cpu_set_n_threads(ggml_backend_t backend_cpu, int n_threads);
  void ggml_backend_cpu_set_threadpool(ggml_backend_t backend_cpu, ggml_threadpool_t threadpool);
  void ggml_backend_cpu_set_abort_callback(ggml_backend_t backend_cpu, ggml_abort_callback abort_callback, void * abort_callback_data);
  void ggml_backend_cpu_set_use_ref(ggml_backend_t backend_cpu, bool use_ref);
  ggml_backend_reg_t ggml_backend_cpu_reg(void);
  void ggml_cpu_fp32_to_fp32(const float *, float *, int64_t);
  void ggml_cpu_fp32_to_i32(const float *, int32_t *, int64_t);
  void ggml_cpu_fp32_to_fp16(const float *, ggml_fp16_t *, int64_t);
  void ggml_cpu_fp16_to_fp32(const ggml_fp16_t *, float *, int64_t);
  void ggml_cpu_fp32_to_bf16(const float *, ggml_bf16_t *, int64_t);
  void ggml_cpu_bf16_to_fp32(const ggml_bf16_t *, float *, int64_t);
  ggml_backend_buffer_t ggml_backend_cpu_buffer_from_ptr(void * ptr, size_t size);
  ggml_backend_buffer_type_t ggml_backend_cpu_buffer_type(void);
]]
local loader = require "ion7.core.ffi.loader"
return loader.ggml
