-- src/ion7/core/ffi/ggml/cuda.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: ggml-cuda.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  ggml_backend_t ggml_backend_cuda_init(int device);
  ggml_backend_buffer_type_t ggml_backend_cuda_buffer_type(int device);
  bool ggml_backend_cuda_allreduce_tensor(ggml_backend_t * backends, struct ggml_tensor ** tensors, size_t n_backends);
  ggml_backend_buffer_type_t ggml_backend_cuda_split_buffer_type(int main_device, const float * tensor_split);
  ggml_backend_buffer_type_t ggml_backend_cuda_host_buffer_type(void);
  int ggml_backend_cuda_get_device_count(void);
  void ggml_backend_cuda_get_device_description(int device, char * description, size_t description_size);
  void ggml_backend_cuda_get_device_memory(int device, size_t * free, size_t * total);
  bool ggml_backend_cuda_register_host_buffer(void * buffer, size_t size);
  void ggml_backend_cuda_unregister_host_buffer(void * buffer);
  ggml_backend_reg_t ggml_backend_cuda_reg(void);
]]
local loader = require "ion7.core.ffi.loader"
return loader.ggml
