-- src/ion7/core/ffi/ggml/graph.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: ggml-cpu.h, ggml.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  struct ggml_cplan ggml_graph_plan(const struct ggml_cgraph * cgraph, int n_threads, struct ggml_threadpool * threadpool);
  enum ggml_status ggml_graph_compute(struct ggml_cgraph * cgraph, struct ggml_cplan * cplan);
  enum ggml_status ggml_graph_compute_with_ctx(struct ggml_context * ctx, struct ggml_cgraph * cgraph, int n_threads);
  struct ggml_tensor * ggml_build_forward_select(struct ggml_cgraph * cgraph, struct ggml_tensor ** tensors, int n_tensors, int idx);
  void ggml_build_forward_expand(struct ggml_cgraph * cgraph, struct ggml_tensor * tensor);
  struct ggml_cgraph * ggml_new_graph(struct ggml_context * ctx);
  struct ggml_cgraph * ggml_new_graph_custom(struct ggml_context * ctx, size_t size, bool grads);
  struct ggml_cgraph * ggml_graph_dup(struct ggml_context * ctx, struct ggml_cgraph * cgraph, bool force_grads);
  void ggml_graph_cpy(struct ggml_cgraph * src, struct ggml_cgraph * dst);
  void ggml_graph_reset(struct ggml_cgraph * cgraph);
  void ggml_graph_clear(struct ggml_cgraph * cgraph);
  int ggml_graph_size(struct ggml_cgraph * cgraph);
  struct ggml_tensor * ggml_graph_node(struct ggml_cgraph * cgraph, int i);
  struct ggml_tensor ** ggml_graph_nodes(struct ggml_cgraph * cgraph);
  int ggml_graph_n_nodes(struct ggml_cgraph * cgraph);
  void ggml_graph_add_node(struct ggml_cgraph * cgraph, struct ggml_tensor * tensor);
  size_t ggml_graph_overhead(void);
  size_t ggml_graph_overhead_custom(size_t size, bool grads);
  struct ggml_tensor * ggml_graph_get_tensor(const struct ggml_cgraph * cgraph, const char * name);
  struct ggml_tensor * ggml_graph_get_grad(const struct ggml_cgraph * cgraph, const struct ggml_tensor * node);
  struct ggml_tensor * ggml_graph_get_grad_acc(const struct ggml_cgraph * cgraph, const struct ggml_tensor * node);
  void ggml_graph_print(const struct ggml_cgraph * cgraph);
  void ggml_graph_dump_dot(const struct ggml_cgraph * gb, const struct ggml_cgraph * cgraph, const char * filename);
]]
local loader = require "ion7.core.ffi.loader"
return loader.ggml
