-- src/ion7/core/ffi/ggml/metal.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: ggml-metal.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  ggml_backend_t ggml_backend_metal_init(void);
  void ggml_backend_metal_set_abort_callback(ggml_backend_t backend, ggml_abort_callback abort_callback, void * user_data);
  bool ggml_backend_metal_supports_family(ggml_backend_t backend, int family);
  void ggml_backend_metal_capture_next_compute(ggml_backend_t backend);
  ggml_backend_reg_t ggml_backend_metal_reg(void);
]]
local loader = require "ion7.core.ffi.loader"
return loader.ggml
