-- src/ion7/core/ffi/ggml/opt.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: ggml-opt.h, ggml.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  ggml_opt_dataset_t ggml_opt_dataset_init(enum ggml_type type_data, enum ggml_type type_label, int64_t ne_datapoint, int64_t ne_label, int64_t ndata, int64_t ndata_shard);
  void ggml_opt_dataset_free(ggml_opt_dataset_t dataset);
  int64_t ggml_opt_dataset_ndata(ggml_opt_dataset_t dataset);
  struct ggml_tensor * ggml_opt_dataset_data(ggml_opt_dataset_t dataset);
  struct ggml_tensor * ggml_opt_dataset_labels(ggml_opt_dataset_t dataset);
  void ggml_opt_dataset_shuffle(ggml_opt_context_t opt_ctx, ggml_opt_dataset_t dataset, int64_t idata);
  void ggml_opt_dataset_get_batch(ggml_opt_dataset_t dataset, struct ggml_tensor * data_batch, struct ggml_tensor * labels_batch, int64_t ibatch);
  void ggml_opt_dataset_get_batch_host(ggml_opt_dataset_t dataset, void * data_batch, size_t nb_data_batch, void * labels_batch, int64_t ibatch);
  struct ggml_opt_optimizer_params ggml_opt_get_default_optimizer_params(void * userdata);
  struct ggml_opt_optimizer_params ggml_opt_get_constant_optimizer_params(void * userdata);
  struct ggml_opt_params ggml_opt_default_params(ggml_backend_sched_t backend_sched, enum ggml_opt_loss_type loss_type);
  ggml_opt_context_t ggml_opt_init(struct ggml_opt_params params);
  void ggml_opt_free(ggml_opt_context_t opt_ctx);
  void ggml_opt_reset(ggml_opt_context_t opt_ctx, bool optimizer);
  bool ggml_opt_static_graphs(ggml_opt_context_t opt_ctx);
  struct ggml_tensor * ggml_opt_inputs(ggml_opt_context_t opt_ctx);
  struct ggml_tensor * ggml_opt_outputs(ggml_opt_context_t opt_ctx);
  struct ggml_tensor * ggml_opt_labels(ggml_opt_context_t opt_ctx);
  struct ggml_tensor * ggml_opt_loss(ggml_opt_context_t opt_ctx);
  struct ggml_tensor * ggml_opt_pred(ggml_opt_context_t opt_ctx);
  struct ggml_tensor * ggml_opt_ncorrect(ggml_opt_context_t opt_ctx);
  struct ggml_tensor * ggml_opt_grad_acc(ggml_opt_context_t opt_ctx, struct ggml_tensor * node);
  enum ggml_opt_optimizer_type ggml_opt_context_optimizer_type(ggml_opt_context_t);
  const char * ggml_opt_optimizer_name(enum ggml_opt_optimizer_type);
  ggml_opt_result_t ggml_opt_result_init(void);
  void ggml_opt_result_free(ggml_opt_result_t result);
  void ggml_opt_result_reset(ggml_opt_result_t result);
  void ggml_opt_result_ndata(ggml_opt_result_t result, int64_t * ndata);
  void ggml_opt_result_loss(ggml_opt_result_t result, double * loss, double * unc);
  void ggml_opt_result_pred(ggml_opt_result_t result, int32_t * pred);
  void ggml_opt_result_accuracy(ggml_opt_result_t result, double * accuracy, double * unc);
  void ggml_opt_prepare_alloc(ggml_opt_context_t opt_ctx, struct ggml_context * ctx_compute, struct ggml_cgraph * gf, struct ggml_tensor * inputs, struct ggml_tensor * outputs);
  void ggml_opt_alloc(ggml_opt_context_t opt_ctx, bool backward);
  void ggml_opt_eval(ggml_opt_context_t opt_ctx, ggml_opt_result_t result);
  void ggml_opt_epoch(ggml_opt_context_t opt_ctx, ggml_opt_dataset_t dataset, ggml_opt_result_t result_train, ggml_opt_result_t result_eval, int64_t idata_split, ggml_opt_epoch_callback callback_train, ggml_opt_epoch_callback callback_eval);
  void ggml_opt_epoch_callback_progress_bar(bool train, ggml_opt_context_t opt_ctx, ggml_opt_dataset_t dataset, ggml_opt_result_t result, int64_t ibatch, int64_t ibatch_max, int64_t t_start_us);
  void ggml_opt_fit(ggml_backend_sched_t backend_sched, struct ggml_context * ctx_compute, struct ggml_tensor * inputs, struct ggml_tensor * outputs, ggml_opt_dataset_t dataset, enum ggml_opt_loss_type loss_type, enum ggml_opt_optimizer_type optimizer, ggml_opt_get_optimizer_params get_opt_pars, int64_t nepoch, int64_t nbatch_logical, float val_split, bool silent);
  struct ggml_tensor * ggml_opt_step_adamw(struct ggml_context * ctx, struct ggml_tensor * a, struct ggml_tensor * grad, struct ggml_tensor * m, struct ggml_tensor * v, struct ggml_tensor * adamw_params);
  struct ggml_tensor * ggml_opt_step_sgd(struct ggml_context * ctx, struct ggml_tensor * a, struct ggml_tensor * grad, struct ggml_tensor * sgd_params);
]]
local loader = require "ion7.core.ffi.loader"
return loader.ggml
