-- src/ion7/core/ffi/ggml/quantize.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: ggml.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  void ggml_quantize_init(enum ggml_type type);
  void ggml_quantize_free(void);
  bool ggml_quantize_requires_imatrix(enum ggml_type type);
  size_t ggml_quantize_chunk(enum ggml_type type, const float * src, void * dst, int64_t start, int64_t nrows, int64_t n_per_row, const float * imatrix);
]]
local loader = require "ion7.core.ffi.loader"
return loader.ggml
