-- src/ion7/core/ffi/ggml/rpc.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: ggml-rpc.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  ggml_backend_t ggml_backend_rpc_init(const char * endpoint, uint32_t device);
  ggml_backend_buffer_type_t ggml_backend_rpc_buffer_type(const char * endpoint, uint32_t device);
  void ggml_backend_rpc_get_device_memory(const char * endpoint, uint32_t device, size_t * free, size_t * total);
  void ggml_backend_rpc_start_server(const char * endpoint, const char * cache_dir, size_t n_threads, size_t n_devices, ggml_backend_dev_t * devices);
  ggml_backend_reg_t ggml_backend_rpc_reg(void);
  ggml_backend_reg_t ggml_backend_rpc_add_server(const char * endpoint);
]]
local loader = require "ion7.core.ffi.loader"
return loader.ggml
