-- src/ion7/core/ffi/ggml/sycl.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: ggml-sycl.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  ggml_backend_t ggml_backend_sycl_init(int device);
  ggml_backend_buffer_type_t ggml_backend_sycl_buffer_type(int device);
  ggml_backend_buffer_type_t ggml_backend_sycl_split_buffer_type(const float * tensor_split);
  ggml_backend_buffer_type_t ggml_backend_sycl_host_buffer_type(void);
  void ggml_backend_sycl_print_sycl_devices(void);
  void ggml_backend_sycl_get_gpu_list(int * id_list, int max_len);
  void ggml_backend_sycl_get_device_description(int device, char * description, size_t description_size);
  int ggml_backend_sycl_get_device_count(void);
  void ggml_backend_sycl_get_device_memory(int device, size_t * free, size_t * total);
  ggml_backend_reg_t ggml_backend_sycl_reg(void);
]]
local loader = require "ion7.core.ffi.loader"
return loader.ggml
