-- src/ion7/core/ffi/ggml/tensor.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: ggml-cpu.h, ggml.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  double ggml_type_sizef(enum ggml_type type);
  bool ggml_is_numa(void);
  struct ggml_tensor * ggml_set_i32(struct ggml_tensor * tensor, int32_t value);
  struct ggml_tensor * ggml_set_f32(struct ggml_tensor * tensor, float value);
  int32_t ggml_get_i32_1d(const struct ggml_tensor * tensor, int i);
  void ggml_set_i32_1d(const struct ggml_tensor * tensor, int i, int32_t value);
  int32_t ggml_get_i32_nd(const struct ggml_tensor * tensor, int i0, int i1, int i2, int i3);
  void ggml_set_i32_nd(const struct ggml_tensor * tensor, int i0, int i1, int i2, int i3, int32_t value);
  float ggml_get_f32_1d(const struct ggml_tensor * tensor, int i);
  void ggml_set_f32_1d(const struct ggml_tensor * tensor, int i, float value);
  float ggml_get_f32_nd(const struct ggml_tensor * tensor, int i0, int i1, int i2, int i3);
  void ggml_set_f32_nd(const struct ggml_tensor * tensor, int i0, int i1, int i2, int i3, float value);
  const struct ggml_type_traits_cpu * ggml_get_type_traits_cpu(enum ggml_type type);
  ggml_abort_callback_t ggml_set_abort_callback(ggml_abort_callback_t callback);
  int64_t ggml_nelements(const struct ggml_tensor * tensor);
  int64_t ggml_nrows(const struct ggml_tensor * tensor);
  size_t ggml_nbytes(const struct ggml_tensor * tensor);
  size_t ggml_nbytes_pad(const struct ggml_tensor * tensor);
  int64_t ggml_blck_size(enum ggml_type type);
  size_t ggml_type_size(enum ggml_type type);
  size_t ggml_row_size(enum ggml_type type, int64_t ne);
  size_t ggml_element_size(const struct ggml_tensor * tensor);
  bool ggml_is_quantized(enum ggml_type type);
  bool ggml_is_transposed(const struct ggml_tensor * tensor);
  bool ggml_is_permuted(const struct ggml_tensor * tensor);
  bool ggml_is_empty(const struct ggml_tensor * tensor);
  bool ggml_is_view(const struct ggml_tensor * tensor);
  bool ggml_is_scalar(const struct ggml_tensor * tensor);
  bool ggml_is_vector(const struct ggml_tensor * tensor);
  bool ggml_is_matrix(const struct ggml_tensor * tensor);
  bool ggml_is_3d(const struct ggml_tensor * tensor);
  int ggml_n_dims(const struct ggml_tensor * tensor);
  bool ggml_is_contiguous(const struct ggml_tensor * tensor);
  bool ggml_is_contiguous_0(const struct ggml_tensor * tensor);
  bool ggml_is_contiguous_1(const struct ggml_tensor * tensor);
  bool ggml_is_contiguous_2(const struct ggml_tensor * tensor);
  bool ggml_is_contiguously_allocated(const struct ggml_tensor * tensor);
  bool ggml_is_contiguous_channels(const struct ggml_tensor * tensor);
  bool ggml_is_contiguous_rows(const struct ggml_tensor * tensor);
  bool ggml_get_no_alloc(struct ggml_context * ctx);
  void ggml_set_no_alloc(struct ggml_context * ctx, bool no_alloc);
  void * ggml_get_mem_buffer(const struct ggml_context * ctx);
  size_t ggml_get_mem_size(const struct ggml_context * ctx);
  size_t ggml_get_max_tensor_size(const struct ggml_context * ctx);
  struct ggml_tensor * ggml_new_tensor(struct ggml_context * ctx, enum ggml_type type, int n_dims, const int64_t * ne);
  struct ggml_tensor * ggml_new_tensor_1d(struct ggml_context * ctx, enum ggml_type type, int64_t ne0);
  struct ggml_tensor * ggml_new_tensor_2d(struct ggml_context * ctx, enum ggml_type type, int64_t ne0, int64_t ne1);
  struct ggml_tensor * ggml_new_tensor_3d(struct ggml_context * ctx, enum ggml_type type, int64_t ne0, int64_t ne1, int64_t ne2);
  struct ggml_tensor * ggml_new_tensor_4d(struct ggml_context * ctx, enum ggml_type type, int64_t ne0, int64_t ne1, int64_t ne2, int64_t ne3);
  struct ggml_tensor * ggml_dup_tensor(struct ggml_context * ctx, const struct ggml_tensor * src);
  struct ggml_tensor * ggml_view_tensor(struct ggml_context * ctx, struct ggml_tensor * src);
  struct ggml_tensor * ggml_get_first_tensor(const struct ggml_context * ctx);
  struct ggml_tensor * ggml_get_next_tensor(const struct ggml_context * ctx, struct ggml_tensor * tensor);
  struct ggml_tensor * ggml_get_tensor(struct ggml_context * ctx, const char * name);
  enum ggml_unary_op ggml_get_unary_op(const struct ggml_tensor * tensor);
  enum ggml_glu_op ggml_get_glu_op(const struct ggml_tensor * tensor);
  void * ggml_get_data(const struct ggml_tensor * tensor);
  float * ggml_get_data_f32(const struct ggml_tensor * tensor);
  const char * ggml_get_name(const struct ggml_tensor * tensor);
  struct ggml_tensor * ggml_set_name(struct ggml_tensor * tensor, const char * name);
  void ggml_set_input(struct ggml_tensor * tensor);
  void ggml_set_output(struct ggml_tensor * tensor);
  void ggml_set_param(struct ggml_tensor * tensor);
  void ggml_set_loss(struct ggml_tensor * tensor);
  struct ggml_tensor * ggml_set_inplace(struct ggml_context * ctx, struct ggml_tensor * a, struct ggml_tensor * b, size_t nb1, size_t nb2, size_t nb3, size_t offset);
  struct ggml_tensor * ggml_set_1d(struct ggml_context * ctx, struct ggml_tensor * a, struct ggml_tensor * b, size_t offset);
  struct ggml_tensor * ggml_set_1d_inplace(struct ggml_context * ctx, struct ggml_tensor * a, struct ggml_tensor * b, size_t offset);
  struct ggml_tensor * ggml_set_2d(struct ggml_context * ctx, struct ggml_tensor * a, struct ggml_tensor * b, size_t nb1, size_t offset);
  struct ggml_tensor * ggml_set_2d_inplace(struct ggml_context * ctx, struct ggml_tensor * a, struct ggml_tensor * b, size_t nb1, size_t offset);
  struct ggml_tensor * ggml_cont(struct ggml_context * ctx, struct ggml_tensor * a);
  struct ggml_tensor * ggml_cont_1d(struct ggml_context * ctx, struct ggml_tensor * a, int64_t ne0);
  struct ggml_tensor * ggml_cont_2d(struct ggml_context * ctx, struct ggml_tensor * a, int64_t ne0, int64_t ne1);
  struct ggml_tensor * ggml_cont_3d(struct ggml_context * ctx, struct ggml_tensor * a, int64_t ne0, int64_t ne1, int64_t ne2);
  struct ggml_tensor * ggml_cont_4d(struct ggml_context * ctx, struct ggml_tensor * a, int64_t ne0, int64_t ne1, int64_t ne2, int64_t ne3);
  struct ggml_tensor * ggml_reshape_1d(struct ggml_context * ctx, struct ggml_tensor * a, int64_t ne0);
  struct ggml_tensor * ggml_reshape_2d(struct ggml_context * ctx, struct ggml_tensor * a, int64_t ne0, int64_t ne1);
  struct ggml_tensor * ggml_reshape_3d(struct ggml_context * ctx, struct ggml_tensor * a, int64_t ne0, int64_t ne1, int64_t ne2);
  struct ggml_tensor * ggml_reshape_4d(struct ggml_context * ctx, struct ggml_tensor * a, int64_t ne0, int64_t ne1, int64_t ne2, int64_t ne3);
  struct ggml_tensor * ggml_view_1d(struct ggml_context * ctx, struct ggml_tensor * a, int64_t ne0, size_t offset);
  struct ggml_tensor * ggml_view_2d(struct ggml_context * ctx, struct ggml_tensor * a, int64_t ne0, int64_t ne1, size_t nb1, size_t offset);
  struct ggml_tensor * ggml_view_3d(struct ggml_context * ctx, struct ggml_tensor * a, int64_t ne0, int64_t ne1, int64_t ne2, size_t nb1, size_t nb2, size_t offset);
  struct ggml_tensor * ggml_view_4d(struct ggml_context * ctx, struct ggml_tensor * a, int64_t ne0, int64_t ne1, int64_t ne2, int64_t ne3, size_t nb1, size_t nb2, size_t nb3, size_t offset);
  struct ggml_tensor * ggml_permute(struct ggml_context * ctx, struct ggml_tensor * a, int axis0, int axis1, int axis2, int axis3);
  struct ggml_tensor * ggml_transpose(struct ggml_context * ctx, struct ggml_tensor * a);
  struct ggml_tensor * ggml_get_rows(struct ggml_context * ctx, struct ggml_tensor * a, struct ggml_tensor * b);
  struct ggml_tensor * ggml_get_rows_back(struct ggml_context * ctx, struct ggml_tensor * a, struct ggml_tensor * b, struct ggml_tensor * c);
  struct ggml_tensor * ggml_set_rows(struct ggml_context * ctx, struct ggml_tensor * a, struct ggml_tensor * b, struct ggml_tensor * c);
  struct ggml_tensor * ggml_get_rel_pos(struct ggml_context * ctx, struct ggml_tensor * a, int qh, int kh);
  struct ggml_tensor * ggml_set_zero(struct ggml_tensor * tensor);
  const struct ggml_type_traits * ggml_get_type_traits(enum ggml_type type);
]]
local loader = require "ion7.core.ffi.loader"
return loader.ggml
