-- src/ion7/core/ffi/ggml/vulkan.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: ggml-vulkan.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  ggml_backend_t ggml_backend_vk_init(size_t dev_num);
  int ggml_backend_vk_get_device_count(void);
  void ggml_backend_vk_get_device_description(int device, char * description, size_t description_size);
  void ggml_backend_vk_get_device_memory(int device, size_t * free, size_t * total);
  ggml_backend_buffer_type_t ggml_backend_vk_buffer_type(size_t dev_num);
  ggml_backend_buffer_type_t ggml_backend_vk_host_buffer_type(void);
  ggml_backend_reg_t ggml_backend_vk_reg(void);
]]
local loader = require "ion7.core.ffi.loader"
return loader.ggml
