-- src/ion7/core/ffi/ggml/webgpu.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: ggml-webgpu.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  ggml_backend_t ggml_backend_webgpu_init(void);
  ggml_backend_reg_t ggml_backend_webgpu_reg(void);
]]
local loader = require "ion7.core.ffi.loader"
return loader.ggml
