-- src/ion7/core/ffi/llama/adapter.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: llama.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  struct llama_adapter_lora * llama_adapter_lora_init(struct llama_model * model, const char * path_lora);
  int32_t llama_adapter_meta_val_str(const struct llama_adapter_lora * adapter, const char * key, char * buf, size_t buf_size);
  int32_t llama_adapter_meta_count(const struct llama_adapter_lora * adapter);
  int32_t llama_adapter_meta_key_by_index(const struct llama_adapter_lora * adapter, int32_t i, char * buf, size_t buf_size);
  int32_t llama_adapter_meta_val_str_by_index(const struct llama_adapter_lora * adapter, int32_t i, char * buf, size_t buf_size);
  void llama_adapter_lora_free(struct llama_adapter_lora * adapter);
  uint64_t llama_adapter_get_alora_n_invocation_tokens(const struct llama_adapter_lora * adapter);
  const llama_token * llama_adapter_get_alora_invocation_tokens(const struct llama_adapter_lora * adapter);
]]
local loader = require "ion7.core.ffi.loader"
return loader.llama
