-- src/ion7/core/ffi/llama/backend.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: llama.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  void llama_backend_init(void);
  void llama_backend_free(void);
  void llama_numa_init(enum ggml_numa_strategy numa);
  int64_t llama_time_us(void);
  size_t llama_max_devices(void);
  size_t llama_max_parallel_sequences(void);
  bool llama_supports_mmap(void);
  bool llama_supports_mlock(void);
  bool llama_supports_gpu_offload(void);
  bool llama_supports_rpc(void);
  int32_t llama_split_path(char * split_path, size_t maxlen, const char * path_prefix, int32_t split_no, int32_t split_count);
  int32_t llama_split_prefix(char * split_prefix, size_t maxlen, const char * split_path, int32_t split_no, int32_t split_count);
  const char * llama_print_system_info(void);
  void llama_log_set(ggml_log_callback log_callback, void * user_data);
]]
local loader = require "ion7.core.ffi.loader"
return loader.llama
