-- src/ion7/core/ffi/llama/batch.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: llama.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  struct llama_batch llama_batch_get_one(llama_token * tokens, int32_t n_tokens);
  struct llama_batch llama_batch_init(int32_t n_tokens, int32_t embd, int32_t n_seq_max);
  void llama_batch_free(struct llama_batch batch);
]]
local loader = require "ion7.core.ffi.loader"
return loader.llama
