-- src/ion7/core/ffi/llama/context.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: llama.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  size_t llama_set_state_data(struct llama_context * ctx, const uint8_t * src);
  struct llama_context * llama_new_context_with_model(struct llama_model * model, struct llama_context_params params);
  int32_t llama_n_ctx_train(const struct llama_model * model);
  struct llama_context_params llama_context_default_params(void);
  void llama_free(struct llama_context * ctx);
  uint32_t llama_n_ctx(const struct llama_context * ctx);
  uint32_t llama_n_ctx_seq(const struct llama_context * ctx);
  uint32_t llama_n_batch(const struct llama_context * ctx);
  uint32_t llama_n_ubatch(const struct llama_context * ctx);
  uint32_t llama_n_seq_max(const struct llama_context * ctx);
  int32_t llama_set_adapters_lora(struct llama_context * ctx, struct llama_adapter_lora ** adapters, size_t n_adapters, float * scales);
  int32_t llama_set_adapter_cvec(struct llama_context * ctx, const float * data, size_t len, int32_t n_embd, int32_t il_start, int32_t il_end);
  int32_t llama_encode(struct llama_context * ctx, struct llama_batch batch);
  int32_t llama_decode(struct llama_context * ctx, struct llama_batch batch);
  void llama_set_n_threads(struct llama_context * ctx, int32_t n_threads, int32_t n_threads_batch);
  void llama_set_embeddings(struct llama_context * ctx, bool embeddings);
  void llama_set_causal_attn(struct llama_context * ctx, bool causal_attn);
  void llama_set_warmup(struct llama_context * ctx, bool warmup);
  void llama_set_abort_callback(struct llama_context * ctx, ggml_abort_callback abort_callback, void * abort_callback_data);
  void llama_synchronize(struct llama_context * ctx);
  bool llama_set_sampler(struct llama_context * ctx, llama_seq_id seq_id, struct llama_sampler * smpl);
]]
local loader = require "ion7.core.ffi.loader"
return loader.llama
