-- src/ion7/core/ffi/llama/kv_cache.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: llama.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  void llama_memory_clear(llama_memory_t mem, bool data);
  bool llama_memory_seq_rm(llama_memory_t mem, llama_seq_id seq_id, llama_pos p0, llama_pos p1);
  void llama_memory_seq_cp(llama_memory_t mem, llama_seq_id seq_id_src, llama_seq_id seq_id_dst, llama_pos p0, llama_pos p1);
  void llama_memory_seq_keep(llama_memory_t mem, llama_seq_id seq_id);
  void llama_memory_seq_add(llama_memory_t mem, llama_seq_id seq_id, llama_pos p0, llama_pos p1, llama_pos delta);
  void llama_memory_seq_div(llama_memory_t mem, llama_seq_id seq_id, llama_pos p0, llama_pos p1, int d);
  llama_pos llama_memory_seq_pos_min(llama_memory_t mem, llama_seq_id seq_id);
  llama_pos llama_memory_seq_pos_max(llama_memory_t mem, llama_seq_id seq_id);
  bool llama_memory_can_shift(llama_memory_t mem);
]]
local loader = require "ion7.core.ffi.loader"
return loader.llama
