-- src/ion7/core/ffi/llama/logits.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: llama.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  float * llama_get_logits(struct llama_context * ctx);
  float * llama_get_logits_ith(struct llama_context * ctx, int32_t i);
  float * llama_get_embeddings(struct llama_context * ctx);
  float * llama_get_embeddings_ith(struct llama_context * ctx, int32_t i);
  float * llama_get_embeddings_seq(struct llama_context * ctx, llama_seq_id seq_id);
]]
local loader = require "ion7.core.ffi.loader"
return loader.llama
