-- src/ion7/core/ffi/llama/misc.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: llama.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  size_t llama_copy_state_data(struct llama_context * ctx, uint8_t * dst);
  int32_t llama_n_embd(const struct llama_model * model);
  int32_t llama_n_layer(const struct llama_model * model);
  int32_t llama_n_head(const struct llama_model * model);
  int32_t llama_n_vocab(const struct llama_vocab * vocab);
  bool llama_add_eos_token(const struct llama_vocab * vocab);
  bool llama_save_session_file(struct llama_context * ctx, const char * path_session, const llama_token * tokens, size_t n_token_count);
  bool llama_load_session_file(struct llama_context * ctx, const char * path_session, llama_token * tokens_out, size_t n_token_capacity, size_t * n_token_count_out);
  bool llama_add_bos_token(const struct llama_vocab * vocab);
  size_t llama_get_state_size(struct llama_context * ctx);
  const char * llama_flash_attn_type_name(enum llama_flash_attn_type flash_attn_type);
  void llama_attach_threadpool(struct llama_context * ctx, ggml_threadpool_t threadpool, ggml_threadpool_t threadpool_batch);
  void llama_detach_threadpool(struct llama_context * ctx);
  struct llama_context * llama_init_from_model(struct llama_model * model, struct llama_context_params params);
  size_t llama_max_tensor_buft_overrides(void);
  const struct llama_model * llama_get_model(const struct llama_context * ctx);
  llama_memory_t llama_get_memory(const struct llama_context * ctx);
  enum llama_pooling_type llama_pooling_type(const struct llama_context * ctx);
  int32_t llama_n_threads(struct llama_context * ctx);
  int32_t llama_n_threads_batch(struct llama_context * ctx);
  llama_token llama_get_sampled_token_ith(struct llama_context * ctx, int32_t i);
  float * llama_get_sampled_probs_ith(struct llama_context * ctx, int32_t i);
  uint32_t llama_get_sampled_probs_count_ith(struct llama_context * ctx, int32_t i);
  float * llama_get_sampled_logits_ith(struct llama_context * ctx, int32_t i);
  uint32_t llama_get_sampled_logits_count_ith(struct llama_context * ctx, int32_t i);
  llama_token * llama_get_sampled_candidates_ith(struct llama_context * ctx, int32_t i);
  uint32_t llama_get_sampled_candidates_count_ith(struct llama_context * ctx, int32_t i);
  void llama_log_get(ggml_log_callback * log_callback, void ** user_data);
]]
local loader = require "ion7.core.ffi.loader"
return loader.llama
