-- src/ion7/core/ffi/llama/model.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: llama.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  void llama_free_model(struct llama_model * model);
  struct llama_model * llama_load_model_from_file(const char * path_model, struct llama_model_params params);
  struct llama_model_params llama_model_default_params(void);
  struct llama_model_quantize_params llama_model_quantize_default_params(void);
  struct llama_model * llama_model_init_from_user(struct gguf_context * metadata, llama_model_set_tensor_data_t set_tensor_data, void * set_tensor_data_ud, struct llama_model_params params);
  struct llama_model * llama_model_load_from_file(const char * path_model, struct llama_model_params params);
  struct llama_model * llama_model_load_from_file_ptr(FILE * file, struct llama_model_params params);
  struct llama_model * llama_model_load_from_splits(const char ** paths, size_t n_paths, struct llama_model_params params);
  void llama_model_save_to_file(const struct llama_model * model, const char * path_model);
  void llama_model_free(struct llama_model * model);
  const struct llama_vocab * llama_model_get_vocab(const struct llama_model * model);
  enum llama_rope_type llama_model_rope_type(const struct llama_model * model);
  int32_t llama_model_n_ctx_train(const struct llama_model * model);
  int32_t llama_model_n_embd(const struct llama_model * model);
  int32_t llama_model_n_embd_inp(const struct llama_model * model);
  int32_t llama_model_n_embd_out(const struct llama_model * model);
  int32_t llama_model_n_layer(const struct llama_model * model);
  int32_t llama_model_n_head(const struct llama_model * model);
  int32_t llama_model_n_head_kv(const struct llama_model * model);
  int32_t llama_model_n_swa(const struct llama_model * model);
  float llama_model_rope_freq_scale_train(const struct llama_model * model);
  uint32_t llama_model_n_cls_out(const struct llama_model * model);
  const char * llama_model_cls_label(const struct llama_model * model, uint32_t i);
  int32_t llama_model_meta_val_str(const struct llama_model * model, const char * key, char * buf, size_t buf_size);
  int32_t llama_model_meta_count(const struct llama_model * model);
  const char * llama_model_meta_key_str(enum llama_model_meta_key key);
  int32_t llama_model_meta_key_by_index(const struct llama_model * model, int32_t i, char * buf, size_t buf_size);
  int32_t llama_model_meta_val_str_by_index(const struct llama_model * model, int32_t i, char * buf, size_t buf_size);
  int32_t llama_model_desc(const struct llama_model * model, char * buf, size_t buf_size);
  uint64_t llama_model_size(const struct llama_model * model);
  const char * llama_model_chat_template(const struct llama_model * model, const char * name);
  uint64_t llama_model_n_params(const struct llama_model * model);
  bool llama_model_has_encoder(const struct llama_model * model);
  bool llama_model_has_decoder(const struct llama_model * model);
  llama_token llama_model_decoder_start_token(const struct llama_model * model);
  bool llama_model_is_recurrent(const struct llama_model * model);
  bool llama_model_is_hybrid(const struct llama_model * model);
  bool llama_model_is_diffusion(const struct llama_model * model);
  uint32_t llama_model_quantize(const char * fname_inp, const char * fname_out, const llama_model_quantize_params * params);
]]
local loader = require "ion7.core.ffi.loader"
return loader.llama
