-- src/ion7/core/ffi/llama/perf.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: llama.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  struct llama_perf_context_data llama_perf_context(const struct llama_context * ctx);
  void llama_perf_context_print(const struct llama_context * ctx);
  void llama_perf_context_reset(struct llama_context * ctx);
  struct llama_perf_sampler_data llama_perf_sampler(const struct llama_sampler * chain);
  void llama_perf_sampler_print(const struct llama_sampler * chain);
  void llama_perf_sampler_reset(struct llama_sampler * chain);
]]
local loader = require "ion7.core.ffi.loader"
return loader.llama
