-- src/ion7/core/ffi/llama/sampler.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: llama.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  struct llama_sampler * llama_sampler_init_grammar_lazy(const struct llama_vocab * vocab, const char * grammar_str, const char * grammar_root, const char ** trigger_words, size_t num_trigger_words, const llama_token * trigger_tokens, size_t num_trigger_tokens);
  struct llama_sampler_chain_params llama_sampler_chain_default_params(void);
  struct llama_sampler * llama_sampler_init(struct llama_sampler_i * iface, llama_sampler_context_t ctx);
  const char * llama_sampler_name(const struct llama_sampler * smpl);
  void llama_sampler_accept(struct llama_sampler * smpl, llama_token token);
  void llama_sampler_apply(struct llama_sampler * smpl, llama_token_data_array * cur_p);
  void llama_sampler_reset(struct llama_sampler * smpl);
  struct llama_sampler * llama_sampler_clone(const struct llama_sampler * smpl);
  void llama_sampler_free(struct llama_sampler * smpl);
  struct llama_sampler * llama_sampler_chain_init(struct llama_sampler_chain_params params);
  void llama_sampler_chain_add(struct llama_sampler * chain, struct llama_sampler * smpl);
  struct llama_sampler * llama_sampler_chain_get(struct llama_sampler * chain, int32_t i);
  int llama_sampler_chain_n(const struct llama_sampler * chain);
  struct llama_sampler * llama_sampler_chain_remove(struct llama_sampler * chain, int32_t i);
  struct llama_sampler * llama_sampler_init_greedy(void);
  struct llama_sampler * llama_sampler_init_dist(uint32_t seed);
  struct llama_sampler * llama_sampler_init_top_k(int32_t k);
  struct llama_sampler * llama_sampler_init_top_p(float p, size_t min_keep);
  struct llama_sampler * llama_sampler_init_min_p(float p, size_t min_keep);
  struct llama_sampler * llama_sampler_init_typical(float p, size_t min_keep);
  struct llama_sampler * llama_sampler_init_temp(float t);
  struct llama_sampler * llama_sampler_init_temp_ext(float t, float delta, float exponent);
  struct llama_sampler * llama_sampler_init_xtc(float p, float t, size_t min_keep, uint32_t seed);
  struct llama_sampler * llama_sampler_init_top_n_sigma(float n);
  struct llama_sampler * llama_sampler_init_mirostat(int32_t n_vocab, uint32_t seed, float tau, float eta, int32_t m);
  struct llama_sampler * llama_sampler_init_mirostat_v2(uint32_t seed, float tau, float eta);
  struct llama_sampler * llama_sampler_init_grammar(const struct llama_vocab * vocab, const char * grammar_str, const char * grammar_root);
  struct llama_sampler * llama_sampler_init_grammar_lazy_patterns(const struct llama_vocab * vocab, const char * grammar_str, const char * grammar_root, const char ** trigger_patterns, size_t num_trigger_patterns, const llama_token * trigger_tokens, size_t num_trigger_tokens);
  struct llama_sampler * llama_sampler_init_penalties(int32_t penalty_last_n, float penalty_repeat, float penalty_freq, float penalty_present);
  struct llama_sampler * llama_sampler_init_dry(const struct llama_vocab * vocab, int32_t n_ctx_train, float dry_multiplier, float dry_base, int32_t dry_allowed_length, int32_t dry_penalty_last_n, const char ** seq_breakers, size_t num_breakers);
  struct llama_sampler * llama_sampler_init_adaptive_p(float target, float decay, uint32_t seed);
  struct llama_sampler * llama_sampler_init_logit_bias(int32_t n_vocab, int32_t n_logit_bias, const llama_logit_bias * logit_bias);
  struct llama_sampler * llama_sampler_init_infill(const struct llama_vocab * vocab);
  uint32_t llama_sampler_get_seed(const struct llama_sampler * smpl);
  llama_token llama_sampler_sample(struct llama_sampler * smpl, struct llama_context * ctx, int32_t idx);
]]
local loader = require "ion7.core.ffi.loader"
return loader.llama
