-- src/ion7/core/ffi/llama/state.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: llama.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  size_t llama_state_get_size(struct llama_context * ctx);
  size_t llama_state_get_data(struct llama_context * ctx, uint8_t * dst, size_t size);
  size_t llama_state_set_data(struct llama_context * ctx, const uint8_t * src, size_t size);
  bool llama_state_load_file(struct llama_context * ctx, const char * path_session, llama_token * tokens_out, size_t n_token_capacity, size_t * n_token_count_out);
  bool llama_state_save_file(struct llama_context * ctx, const char * path_session, const llama_token * tokens, size_t n_token_count);
  size_t llama_state_seq_get_size(struct llama_context * ctx, llama_seq_id seq_id);
  size_t llama_state_seq_get_data(struct llama_context * ctx, uint8_t * dst, size_t size, llama_seq_id seq_id);
  size_t llama_state_seq_set_data(struct llama_context * ctx, const uint8_t * src, size_t size, llama_seq_id dest_seq_id);
  size_t llama_state_seq_save_file(struct llama_context * ctx, const char * filepath, llama_seq_id seq_id, const llama_token * tokens, size_t n_token_count);
  size_t llama_state_seq_load_file(struct llama_context * ctx, const char * filepath, llama_seq_id dest_seq_id, llama_token * tokens_out, size_t n_token_capacity, size_t * n_token_count_out);
  size_t llama_state_seq_get_size_ext(struct llama_context * ctx, llama_seq_id seq_id, llama_state_seq_flags flags);
  size_t llama_state_seq_get_data_ext(struct llama_context * ctx, uint8_t * dst, size_t size, llama_seq_id seq_id, llama_state_seq_flags flags);
  size_t llama_state_seq_set_data_ext(struct llama_context * ctx, const uint8_t * src, size_t size, llama_seq_id dest_seq_id, llama_state_seq_flags flags);
]]
local loader = require "ion7.core.ffi.loader"
return loader.llama
