-- src/ion7/core/ffi/llama/vocab.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: llama.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  llama_token llama_token_fim_sep(const struct llama_vocab * vocab);
  bool llama_token_is_control(const struct llama_vocab * vocab, llama_token token);
  llama_token llama_token_bos(const struct llama_vocab * vocab);
  llama_token llama_token_eos(const struct llama_vocab * vocab);
  bool llama_token_is_eog(const struct llama_vocab * vocab, llama_token token);
  float llama_token_get_score(const struct llama_vocab * vocab, llama_token token);
  enum llama_token_attr llama_token_get_attr(const struct llama_vocab * vocab, llama_token token);
  const char * llama_token_get_text(const struct llama_vocab * vocab, llama_token token);
  llama_token llama_vocab_cls(const struct llama_vocab * vocab);
  llama_token llama_token_eot(const struct llama_vocab * vocab);
  llama_token llama_token_sep(const struct llama_vocab * vocab);
  llama_token llama_token_fim_mid(const struct llama_vocab * vocab);
  llama_token llama_token_fim_pad(const struct llama_vocab * vocab);
  llama_token llama_token_cls(const struct llama_vocab * vocab);
  llama_token llama_token_fim_suf(const struct llama_vocab * vocab);
  llama_token llama_token_pad(const struct llama_vocab * vocab);
  llama_token llama_token_fim_pre(const struct llama_vocab * vocab);
  llama_token llama_token_nl(const struct llama_vocab * vocab);
  llama_token llama_token_fim_rep(const struct llama_vocab * vocab);
  enum llama_vocab_type llama_vocab_type(const struct llama_vocab * vocab);
  int32_t llama_vocab_n_tokens(const struct llama_vocab * vocab);
  const char * llama_vocab_get_text(const struct llama_vocab * vocab, llama_token token);
  float llama_vocab_get_score(const struct llama_vocab * vocab, llama_token token);
  enum llama_token_attr llama_vocab_get_attr(const struct llama_vocab * vocab, llama_token token);
  bool llama_vocab_is_eog(const struct llama_vocab * vocab, llama_token token);
  bool llama_vocab_is_control(const struct llama_vocab * vocab, llama_token token);
  llama_token llama_vocab_bos(const struct llama_vocab * vocab);
  llama_token llama_vocab_eos(const struct llama_vocab * vocab);
  llama_token llama_vocab_eot(const struct llama_vocab * vocab);
  llama_token llama_vocab_sep(const struct llama_vocab * vocab);
  llama_token llama_vocab_nl(const struct llama_vocab * vocab);
  llama_token llama_vocab_pad(const struct llama_vocab * vocab);
  llama_token llama_vocab_mask(const struct llama_vocab * vocab);
  bool llama_vocab_get_add_bos(const struct llama_vocab * vocab);
  bool llama_vocab_get_add_eos(const struct llama_vocab * vocab);
  bool llama_vocab_get_add_sep(const struct llama_vocab * vocab);
  llama_token llama_vocab_fim_pre(const struct llama_vocab * vocab);
  llama_token llama_vocab_fim_suf(const struct llama_vocab * vocab);
  llama_token llama_vocab_fim_mid(const struct llama_vocab * vocab);
  llama_token llama_vocab_fim_pad(const struct llama_vocab * vocab);
  llama_token llama_vocab_fim_rep(const struct llama_vocab * vocab);
  llama_token llama_vocab_fim_sep(const struct llama_vocab * vocab);
  int32_t llama_tokenize(const struct llama_vocab * vocab, const char * text, int32_t text_len, llama_token * tokens, int32_t n_tokens_max, bool add_special, bool parse_special);
  int32_t llama_token_to_piece(const struct llama_vocab * vocab, llama_token token, char * buf, int32_t length, int32_t lstrip, bool special);
  int32_t llama_detokenize(const struct llama_vocab * vocab, const llama_token * tokens, int32_t n_tokens, char * text, int32_t text_len_max, bool remove_special, bool unparse_special);
]]
local loader = require "ion7.core.ffi.loader"
return loader.llama
