-- src/ion7/core/ffi/gguf/gguf.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: gguf.h

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are declared first

ffi.cdef[[
  struct gguf_context * gguf_init_empty(void);
  struct gguf_context * gguf_init_from_file_ptr(FILE * file, struct gguf_init_params params);
  struct gguf_context * gguf_init_from_file(const char * fname, struct gguf_init_params params);
  void gguf_free(struct gguf_context * ctx);
  const char * gguf_type_name(enum gguf_type type);
  uint32_t gguf_get_version(const struct gguf_context * ctx);
  size_t gguf_get_alignment(const struct gguf_context * ctx);
  size_t gguf_get_data_offset(const struct gguf_context * ctx);
  int64_t gguf_get_n_kv(const struct gguf_context * ctx);
  int64_t gguf_find_key(const struct gguf_context * ctx, const char * key);
  const char * gguf_get_key(const struct gguf_context * ctx, int64_t key_id);
  enum gguf_type gguf_get_kv_type(const struct gguf_context * ctx, int64_t key_id);
  enum gguf_type gguf_get_arr_type(const struct gguf_context * ctx, int64_t key_id);
  uint8_t gguf_get_val_u8(const struct gguf_context * ctx, int64_t key_id);
  int8_t gguf_get_val_i8(const struct gguf_context * ctx, int64_t key_id);
  uint16_t gguf_get_val_u16(const struct gguf_context * ctx, int64_t key_id);
  int16_t gguf_get_val_i16(const struct gguf_context * ctx, int64_t key_id);
  uint32_t gguf_get_val_u32(const struct gguf_context * ctx, int64_t key_id);
  int32_t gguf_get_val_i32(const struct gguf_context * ctx, int64_t key_id);
  float gguf_get_val_f32(const struct gguf_context * ctx, int64_t key_id);
  uint64_t gguf_get_val_u64(const struct gguf_context * ctx, int64_t key_id);
  int64_t gguf_get_val_i64(const struct gguf_context * ctx, int64_t key_id);
  double gguf_get_val_f64(const struct gguf_context * ctx, int64_t key_id);
  bool gguf_get_val_bool(const struct gguf_context * ctx, int64_t key_id);
  const char * gguf_get_val_str(const struct gguf_context * ctx, int64_t key_id);
  const void * gguf_get_val_data(const struct gguf_context * ctx, int64_t key_id);
  size_t gguf_get_arr_n(const struct gguf_context * ctx, int64_t key_id);
  const void * gguf_get_arr_data(const struct gguf_context * ctx, int64_t key_id);
  const char * gguf_get_arr_str(const struct gguf_context * ctx, int64_t key_id, size_t i);
  int64_t gguf_get_n_tensors(const struct gguf_context * ctx);
  int64_t gguf_find_tensor(const struct gguf_context * ctx, const char * name);
  size_t gguf_get_tensor_offset(const struct gguf_context * ctx, int64_t tensor_id);
  const char * gguf_get_tensor_name(const struct gguf_context * ctx, int64_t tensor_id);
  enum ggml_type gguf_get_tensor_type(const struct gguf_context * ctx, int64_t tensor_id);
  size_t gguf_get_tensor_size(const struct gguf_context * ctx, int64_t tensor_id);
  int64_t gguf_remove_key(struct gguf_context * ctx, const char * key);
  void gguf_set_val_u8(struct gguf_context * ctx, const char * key, uint8_t val);
  void gguf_set_val_i8(struct gguf_context * ctx, const char * key, int8_t val);
  void gguf_set_val_u16(struct gguf_context * ctx, const char * key, uint16_t val);
  void gguf_set_val_i16(struct gguf_context * ctx, const char * key, int16_t val);
  void gguf_set_val_u32(struct gguf_context * ctx, const char * key, uint32_t val);
  void gguf_set_val_i32(struct gguf_context * ctx, const char * key, int32_t val);
  void gguf_set_val_f32(struct gguf_context * ctx, const char * key, float val);
  void gguf_set_val_u64(struct gguf_context * ctx, const char * key, uint64_t val);
  void gguf_set_val_i64(struct gguf_context * ctx, const char * key, int64_t val);
  void gguf_set_val_f64(struct gguf_context * ctx, const char * key, double val);
  void gguf_set_val_bool(struct gguf_context * ctx, const char * key, bool val);
  void gguf_set_val_str(struct gguf_context * ctx, const char * key, const char * val);
  void gguf_set_arr_data(struct gguf_context * ctx, const char * key, enum gguf_type type, const void * data, size_t n);
  void gguf_set_arr_str(struct gguf_context * ctx, const char * key, const char ** data, size_t n);
  void gguf_set_kv(struct gguf_context * ctx, const struct gguf_context * src);
  void gguf_add_tensor(struct gguf_context * ctx, const struct ggml_tensor * tensor);
  void gguf_set_tensor_type(struct gguf_context * ctx, const char * name, enum ggml_type type);
  void gguf_set_tensor_data(struct gguf_context * ctx, const char * name, const void * data);
  bool gguf_write_to_file_ptr(const struct gguf_context * ctx, FILE * file, bool only_meta);
  bool gguf_write_to_file(const struct gguf_context * ctx, const char * fname, bool only_meta);
  size_t gguf_get_meta_size(const struct gguf_context * ctx);
  void gguf_get_meta_data(const struct gguf_context * ctx, void * data);
]]
local loader = require "ion7.core.ffi.loader"
return loader.gguf
