-- src/ion7/core/ffi/types.lua
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: llama.h, ggml.h and the public ggml-* headers

local ffi = require "ffi"

ffi.cdef[[
  -- Forward declarations
  struct ggml_object;
  struct ggml_context;
  struct ggml_cgraph;
  struct ggml_threadpool;
  struct ggml_backend_buffer_type;
  struct ggml_backend;
  struct ggml_gallocr;
  struct ggml_backend_event;
  struct ggml_backend_reg;
  struct ggml_backend_device;
  struct ggml_backend_sched;
  struct ggml_opt_dataset;
  struct ggml_opt_context;
  struct ggml_opt_result;
  struct gguf_context;
  struct llama_vocab;
  struct llama_model;
  struct llama_context;
  struct llama_memory_i;
  struct llama_adapter_lora;

  -- Enums
  enum ggml_status {
      GGML_STATUS_ALLOC_FAILED = -2,
      GGML_STATUS_FAILED = -1,
      GGML_STATUS_SUCCESS = 0,
      GGML_STATUS_ABORTED = 1,
  };
  enum ggml_type {
      GGML_TYPE_F32 = 0,
      GGML_TYPE_F16 = 1,
      GGML_TYPE_Q4_0 = 2,
      GGML_TYPE_Q4_1 = 3,
      GGML_TYPE_Q5_0 = 6,
      GGML_TYPE_Q5_1 = 7,
      GGML_TYPE_Q8_0 = 8,
      GGML_TYPE_Q8_1 = 9,
      GGML_TYPE_Q2_K = 10,
      GGML_TYPE_Q3_K = 11,
      GGML_TYPE_Q4_K = 12,
      GGML_TYPE_Q5_K = 13,
      GGML_TYPE_Q6_K = 14,
      GGML_TYPE_Q8_K = 15,
      GGML_TYPE_IQ2_XXS = 16,
      GGML_TYPE_IQ2_XS = 17,
      GGML_TYPE_IQ3_XXS = 18,
      GGML_TYPE_IQ1_S = 19,
      GGML_TYPE_IQ4_NL = 20,
      GGML_TYPE_IQ3_S = 21,
      GGML_TYPE_IQ2_S = 22,
      GGML_TYPE_IQ4_XS = 23,
      GGML_TYPE_I8 = 24,
      GGML_TYPE_I16 = 25,
      GGML_TYPE_I32 = 26,
      GGML_TYPE_I64 = 27,
      GGML_TYPE_F64 = 28,
      GGML_TYPE_IQ1_M = 29,
      GGML_TYPE_BF16 = 30,
      GGML_TYPE_TQ1_0 = 34,
      GGML_TYPE_TQ2_0 = 35,
      GGML_TYPE_MXFP4 = 39,
      GGML_TYPE_NVFP4 = 40,
      GGML_TYPE_Q1_0 = 41,
      GGML_TYPE_COUNT = 42,
  };
  enum ggml_prec {
      GGML_PREC_DEFAULT = 0,
      GGML_PREC_F32 = 10,
  };
  enum ggml_ftype {
      GGML_FTYPE_UNKNOWN = -1,
      GGML_FTYPE_ALL_F32 = 0,
      GGML_FTYPE_MOSTLY_F16 = 1,
      GGML_FTYPE_MOSTLY_Q4_0 = 2,
      GGML_FTYPE_MOSTLY_Q4_1 = 3,
      GGML_FTYPE_MOSTLY_Q4_1_SOME_F16 = 4,
      GGML_FTYPE_MOSTLY_Q8_0 = 7,
      GGML_FTYPE_MOSTLY_Q5_0 = 8,
      GGML_FTYPE_MOSTLY_Q5_1 = 9,
      GGML_FTYPE_MOSTLY_Q2_K = 10,
      GGML_FTYPE_MOSTLY_Q3_K = 11,
      GGML_FTYPE_MOSTLY_Q4_K = 12,
      GGML_FTYPE_MOSTLY_Q5_K = 13,
      GGML_FTYPE_MOSTLY_Q6_K = 14,
      GGML_FTYPE_MOSTLY_IQ2_XXS = 15,
      GGML_FTYPE_MOSTLY_IQ2_XS = 16,
      GGML_FTYPE_MOSTLY_IQ3_XXS = 17,
      GGML_FTYPE_MOSTLY_IQ1_S = 18,
      GGML_FTYPE_MOSTLY_IQ4_NL = 19,
      GGML_FTYPE_MOSTLY_IQ3_S = 20,
      GGML_FTYPE_MOSTLY_IQ2_S = 21,
      GGML_FTYPE_MOSTLY_IQ4_XS = 22,
      GGML_FTYPE_MOSTLY_IQ1_M = 23,
      GGML_FTYPE_MOSTLY_BF16 = 24,
      GGML_FTYPE_MOSTLY_MXFP4 = 25,
      GGML_FTYPE_MOSTLY_NVFP4 = 26,
      GGML_FTYPE_MOSTLY_Q1_0 = 27,
  };
  enum ggml_op {
      GGML_OP_NONE = 0,
      GGML_OP_DUP = 0,
      GGML_OP_ADD = 0,
      GGML_OP_ADD_ID = 0,
      GGML_OP_ADD1 = 0,
      GGML_OP_ACC = 0,
      GGML_OP_SUB = 0,
      GGML_OP_MUL = 0,
      GGML_OP_DIV = 0,
      GGML_OP_SQR = 0,
      GGML_OP_SQRT = 0,
      GGML_OP_LOG = 0,
      GGML_OP_SIN = 0,
      GGML_OP_COS = 0,
      GGML_OP_SUM = 0,
      GGML_OP_SUM_ROWS = 0,
      GGML_OP_CUMSUM = 0,
      GGML_OP_MEAN = 0,
      GGML_OP_ARGMAX = 0,
      GGML_OP_COUNT_EQUAL = 0,
      GGML_OP_REPEAT = 0,
      GGML_OP_REPEAT_BACK = 0,
      GGML_OP_CONCAT = 0,
      GGML_OP_SILU_BACK = 0,
      GGML_OP_NORM = 0,
      GGML_OP_RMS_NORM = 0,
      GGML_OP_RMS_NORM_BACK = 0,
      GGML_OP_GROUP_NORM = 0,
      GGML_OP_L2_NORM = 0,
      GGML_OP_MUL_MAT = 0,
      GGML_OP_MUL_MAT_ID = 0,
      GGML_OP_OUT_PROD = 0,
      GGML_OP_SCALE = 0,
      GGML_OP_SET = 0,
      GGML_OP_CPY = 0,
      GGML_OP_CONT = 0,
      GGML_OP_RESHAPE = 0,
      GGML_OP_VIEW = 0,
      GGML_OP_PERMUTE = 0,
      GGML_OP_TRANSPOSE = 0,
      GGML_OP_GET_ROWS = 0,
      GGML_OP_GET_ROWS_BACK = 0,
      GGML_OP_SET_ROWS = 0,
      GGML_OP_DIAG = 0,
      GGML_OP_DIAG_MASK_INF = 0,
      GGML_OP_DIAG_MASK_ZERO = 0,
      GGML_OP_SOFT_MAX = 0,
      GGML_OP_SOFT_MAX_BACK = 0,
      GGML_OP_ROPE = 0,
      GGML_OP_ROPE_BACK = 0,
      GGML_OP_CLAMP = 0,
      GGML_OP_CONV_TRANSPOSE_1D = 0,
      GGML_OP_IM2COL = 0,
      GGML_OP_IM2COL_BACK = 0,
      GGML_OP_IM2COL_3D = 0,
      GGML_OP_CONV_2D = 0,
      GGML_OP_CONV_3D = 0,
      GGML_OP_CONV_2D_DW = 0,
      GGML_OP_CONV_TRANSPOSE_2D = 0,
      GGML_OP_POOL_1D = 0,
      GGML_OP_POOL_2D = 0,
      GGML_OP_POOL_2D_BACK = 0,
      GGML_OP_UPSCALE = 0,
      GGML_OP_PAD = 0,
      GGML_OP_PAD_REFLECT_1D = 0,
      GGML_OP_ROLL = 0,
      GGML_OP_ARANGE = 0,
      GGML_OP_TIMESTEP_EMBEDDING = 0,
      GGML_OP_ARGSORT = 0,
      GGML_OP_TOP_K = 0,
      GGML_OP_LEAKY_RELU = 0,
      GGML_OP_TRI = 0,
      GGML_OP_FILL = 0,
      GGML_OP_FLASH_ATTN_EXT = 0,
      GGML_OP_FLASH_ATTN_BACK = 0,
      GGML_OP_SSM_CONV = 0,
      GGML_OP_SSM_SCAN = 0,
      GGML_OP_WIN_PART = 0,
      GGML_OP_WIN_UNPART = 0,
      GGML_OP_GET_REL_POS = 0,
      GGML_OP_ADD_REL_POS = 0,
      GGML_OP_RWKV_WKV6 = 0,
      GGML_OP_GATED_LINEAR_ATTN = 0,
      GGML_OP_RWKV_WKV7 = 0,
      GGML_OP_SOLVE_TRI = 0,
      GGML_OP_GATED_DELTA_NET = 0,
      GGML_OP_UNARY = 0,
      GGML_OP_MAP_CUSTOM1 = 0,
      GGML_OP_MAP_CUSTOM2 = 0,
      GGML_OP_MAP_CUSTOM3 = 0,
      GGML_OP_CUSTOM = 0,
      GGML_OP_CROSS_ENTROPY_LOSS = 0,
      GGML_OP_CROSS_ENTROPY_LOSS_BACK = 0,
      GGML_OP_OPT_STEP_ADAMW = 0,
      GGML_OP_OPT_STEP_SGD = 0,
      GGML_OP_GLU = 0,
      GGML_OP_COUNT = 0,
  };
  enum ggml_unary_op {
      GGML_UNARY_OP_ABS = 0,
      GGML_UNARY_OP_SGN = 0,
      GGML_UNARY_OP_NEG = 0,
      GGML_UNARY_OP_STEP = 0,
      GGML_UNARY_OP_TANH = 0,
      GGML_UNARY_OP_ELU = 0,
      GGML_UNARY_OP_RELU = 0,
      GGML_UNARY_OP_SIGMOID = 0,
      GGML_UNARY_OP_GELU = 0,
      GGML_UNARY_OP_GELU_QUICK = 0,
      GGML_UNARY_OP_SILU = 0,
      GGML_UNARY_OP_HARDSWISH = 0,
      GGML_UNARY_OP_HARDSIGMOID = 0,
      GGML_UNARY_OP_EXP = 0,
      GGML_UNARY_OP_EXPM1 = 0,
      GGML_UNARY_OP_SOFTPLUS = 0,
      GGML_UNARY_OP_GELU_ERF = 0,
      GGML_UNARY_OP_XIELU = 0,
      GGML_UNARY_OP_FLOOR = 0,
      GGML_UNARY_OP_CEIL = 0,
      GGML_UNARY_OP_ROUND = 0,
      GGML_UNARY_OP_TRUNC = 0,
      GGML_UNARY_OP_COUNT = 0,
  };
  enum ggml_glu_op {
      GGML_GLU_OP_REGLU = 0,
      GGML_GLU_OP_GEGLU = 0,
      GGML_GLU_OP_SWIGLU = 0,
      GGML_GLU_OP_SWIGLU_OAI = 0,
      GGML_GLU_OP_GEGLU_ERF = 0,
      GGML_GLU_OP_GEGLU_QUICK = 0,
      GGML_GLU_OP_COUNT = 0,
  };
  enum ggml_object_type {
      GGML_OBJECT_TYPE_TENSOR = 0,
      GGML_OBJECT_TYPE_GRAPH = 0,
      GGML_OBJECT_TYPE_WORK_BUFFER = 0,
  };
  enum ggml_log_level {
      GGML_LOG_LEVEL_NONE = 0,
      GGML_LOG_LEVEL_DEBUG = 1,
      GGML_LOG_LEVEL_INFO = 2,
      GGML_LOG_LEVEL_WARN = 3,
      GGML_LOG_LEVEL_ERROR = 4,
      GGML_LOG_LEVEL_CONT = 5,
  };
  enum ggml_tensor_flag {
      GGML_TENSOR_FLAG_INPUT = 1,
      GGML_TENSOR_FLAG_OUTPUT = 2,
      GGML_TENSOR_FLAG_PARAM = 4,
      GGML_TENSOR_FLAG_LOSS = 8,
      GGML_TENSOR_FLAG_COMPUTE = 16,
  };
  enum ggml_tri_type {
      GGML_TRI_TYPE_UPPER_DIAG = 0,
      GGML_TRI_TYPE_UPPER = 1,
      GGML_TRI_TYPE_LOWER_DIAG = 2,
      GGML_TRI_TYPE_LOWER = 3,
  };
  enum ggml_op_pool {
      GGML_OP_POOL_MAX = 0,
      GGML_OP_POOL_AVG = 0,
      GGML_OP_POOL_COUNT = 0,
  };
  enum ggml_scale_mode {
      GGML_SCALE_MODE_NEAREST = 0,
      GGML_SCALE_MODE_BILINEAR = 1,
      GGML_SCALE_MODE_BICUBIC = 2,
      GGML_SCALE_MODE_COUNT = 0,
  };
  enum ggml_scale_flag {
      GGML_SCALE_FLAG_ALIGN_CORNERS = 256,
      GGML_SCALE_FLAG_ANTIALIAS = 512,
  };
  enum ggml_sort_order {
      GGML_SORT_ORDER_ASC = 0,
      GGML_SORT_ORDER_DESC = 0,
  };
  enum ggml_sched_priority {
      GGML_SCHED_PRIO_LOW = -1,
      GGML_SCHED_PRIO_NORMAL = 0,
      GGML_SCHED_PRIO_MEDIUM = 0,
      GGML_SCHED_PRIO_HIGH = 0,
      GGML_SCHED_PRIO_REALTIME = 0,
  };
  enum ggml_backend_buffer_usage {
      GGML_BACKEND_BUFFER_USAGE_ANY = 0,
      GGML_BACKEND_BUFFER_USAGE_WEIGHTS = 1,
      GGML_BACKEND_BUFFER_USAGE_COMPUTE = 2,
  };
  enum ggml_backend_dev_type {
      GGML_BACKEND_DEVICE_TYPE_CPU = 0,
      GGML_BACKEND_DEVICE_TYPE_GPU = 0,
      GGML_BACKEND_DEVICE_TYPE_IGPU = 0,
      GGML_BACKEND_DEVICE_TYPE_ACCEL = 0,
      GGML_BACKEND_DEVICE_TYPE_META = 0,
  };
  enum ggml_backend_meta_split_axis {
      GGML_BACKEND_SPLIT_AXIS_0 = 0,
      GGML_BACKEND_SPLIT_AXIS_1 = 1,
      GGML_BACKEND_SPLIT_AXIS_2 = 2,
      GGML_BACKEND_SPLIT_AXIS_3 = 3,
      GGML_BACKEND_SPLIT_AXIS_MIRRORED = 10,
      GGML_BACKEND_SPLIT_AXIS_PARTIAL = 11,
      GGML_BACKEND_SPLIT_AXIS_NONE = 98,
      GGML_BACKEND_SPLIT_AXIS_UNKNOWN = 99,
  };
  enum ggml_numa_strategy {
      GGML_NUMA_STRATEGY_DISABLED = 0,
      GGML_NUMA_STRATEGY_DISTRIBUTE = 1,
      GGML_NUMA_STRATEGY_ISOLATE = 2,
      GGML_NUMA_STRATEGY_NUMACTL = 3,
      GGML_NUMA_STRATEGY_MIRROR = 4,
      GGML_NUMA_STRATEGY_COUNT = 0,
  };
  enum ggml_opt_loss_type {
      GGML_OPT_LOSS_TYPE_MEAN = 0,
      GGML_OPT_LOSS_TYPE_SUM = 0,
      GGML_OPT_LOSS_TYPE_CROSS_ENTROPY = 0,
      GGML_OPT_LOSS_TYPE_MEAN_SQUARED_ERROR = 0,
  };
  enum ggml_opt_build_type {
      GGML_OPT_BUILD_TYPE_FORWARD = 10,
      GGML_OPT_BUILD_TYPE_GRAD = 20,
      GGML_OPT_BUILD_TYPE_OPT = 30,
  };
  enum ggml_opt_optimizer_type {
      GGML_OPT_OPTIMIZER_TYPE_ADAMW = 0,
      GGML_OPT_OPTIMIZER_TYPE_SGD = 0,
      GGML_OPT_OPTIMIZER_TYPE_COUNT = 0,
  };
  enum gguf_type {
      GGUF_TYPE_UINT8 = 0,
      GGUF_TYPE_INT8 = 1,
      GGUF_TYPE_UINT16 = 2,
      GGUF_TYPE_INT16 = 3,
      GGUF_TYPE_UINT32 = 4,
      GGUF_TYPE_INT32 = 5,
      GGUF_TYPE_FLOAT32 = 6,
      GGUF_TYPE_BOOL = 7,
      GGUF_TYPE_STRING = 8,
      GGUF_TYPE_ARRAY = 9,
      GGUF_TYPE_UINT64 = 10,
      GGUF_TYPE_INT64 = 11,
      GGUF_TYPE_FLOAT64 = 12,
      GGUF_TYPE_COUNT = 0,
  };
  enum llama_vocab_type {
      LLAMA_VOCAB_TYPE_NONE = 0,
      LLAMA_VOCAB_TYPE_SPM = 1,
      LLAMA_VOCAB_TYPE_BPE = 2,
      LLAMA_VOCAB_TYPE_WPM = 3,
      LLAMA_VOCAB_TYPE_UGM = 4,
      LLAMA_VOCAB_TYPE_RWKV = 5,
      LLAMA_VOCAB_TYPE_PLAMO2 = 6,
  };
  enum llama_rope_type {
      LLAMA_ROPE_TYPE_NONE = -1,
      LLAMA_ROPE_TYPE_NORM = 0,
      LLAMA_ROPE_TYPE_NEOX = 2,
      LLAMA_ROPE_TYPE_MROPE = 8,
      LLAMA_ROPE_TYPE_IMROPE = 40,
      LLAMA_ROPE_TYPE_VISION = 24,
  };
  enum llama_token_type {
      LLAMA_TOKEN_TYPE_UNDEFINED = 0,
      LLAMA_TOKEN_TYPE_NORMAL = 1,
      LLAMA_TOKEN_TYPE_UNKNOWN = 2,
      LLAMA_TOKEN_TYPE_CONTROL = 3,
      LLAMA_TOKEN_TYPE_USER_DEFINED = 4,
      LLAMA_TOKEN_TYPE_UNUSED = 5,
      LLAMA_TOKEN_TYPE_BYTE = 6,
  };
  enum llama_token_attr {
      LLAMA_TOKEN_ATTR_UNDEFINED = 0,
      LLAMA_TOKEN_ATTR_UNKNOWN = 1,
      LLAMA_TOKEN_ATTR_UNUSED = 2,
      LLAMA_TOKEN_ATTR_NORMAL = 4,
      LLAMA_TOKEN_ATTR_CONTROL = 8,
      LLAMA_TOKEN_ATTR_USER_DEFINED = 16,
      LLAMA_TOKEN_ATTR_BYTE = 32,
      LLAMA_TOKEN_ATTR_NORMALIZED = 64,
      LLAMA_TOKEN_ATTR_LSTRIP = 128,
      LLAMA_TOKEN_ATTR_RSTRIP = 256,
      LLAMA_TOKEN_ATTR_SINGLE_WORD = 512,
  };
  enum llama_ftype {
      LLAMA_FTYPE_ALL_F32 = 0,
      LLAMA_FTYPE_MOSTLY_F16 = 1,
      LLAMA_FTYPE_MOSTLY_Q4_0 = 2,
      LLAMA_FTYPE_MOSTLY_Q4_1 = 3,
      LLAMA_FTYPE_MOSTLY_Q8_0 = 7,
      LLAMA_FTYPE_MOSTLY_Q5_0 = 8,
      LLAMA_FTYPE_MOSTLY_Q5_1 = 9,
      LLAMA_FTYPE_MOSTLY_Q2_K = 10,
      LLAMA_FTYPE_MOSTLY_Q3_K_S = 11,
      LLAMA_FTYPE_MOSTLY_Q3_K_M = 12,
      LLAMA_FTYPE_MOSTLY_Q3_K_L = 13,
      LLAMA_FTYPE_MOSTLY_Q4_K_S = 14,
      LLAMA_FTYPE_MOSTLY_Q4_K_M = 15,
      LLAMA_FTYPE_MOSTLY_Q5_K_S = 16,
      LLAMA_FTYPE_MOSTLY_Q5_K_M = 17,
      LLAMA_FTYPE_MOSTLY_Q6_K = 18,
      LLAMA_FTYPE_MOSTLY_IQ2_XXS = 19,
      LLAMA_FTYPE_MOSTLY_IQ2_XS = 20,
      LLAMA_FTYPE_MOSTLY_Q2_K_S = 21,
      LLAMA_FTYPE_MOSTLY_IQ3_XS = 22,
      LLAMA_FTYPE_MOSTLY_IQ3_XXS = 23,
      LLAMA_FTYPE_MOSTLY_IQ1_S = 24,
      LLAMA_FTYPE_MOSTLY_IQ4_NL = 25,
      LLAMA_FTYPE_MOSTLY_IQ3_S = 26,
      LLAMA_FTYPE_MOSTLY_IQ3_M = 27,
      LLAMA_FTYPE_MOSTLY_IQ2_S = 28,
      LLAMA_FTYPE_MOSTLY_IQ2_M = 29,
      LLAMA_FTYPE_MOSTLY_IQ4_XS = 30,
      LLAMA_FTYPE_MOSTLY_IQ1_M = 31,
      LLAMA_FTYPE_MOSTLY_BF16 = 32,
      LLAMA_FTYPE_MOSTLY_TQ1_0 = 36,
      LLAMA_FTYPE_MOSTLY_TQ2_0 = 37,
      LLAMA_FTYPE_MOSTLY_MXFP4_MOE = 38,
      LLAMA_FTYPE_MOSTLY_NVFP4 = 39,
      LLAMA_FTYPE_MOSTLY_Q1_0 = 40,
      LLAMA_FTYPE_GUESSED = 1024,
  };
  enum llama_rope_scaling_type {
      LLAMA_ROPE_SCALING_TYPE_UNSPECIFIED = -1,
      LLAMA_ROPE_SCALING_TYPE_NONE = 0,
      LLAMA_ROPE_SCALING_TYPE_LINEAR = 1,
      LLAMA_ROPE_SCALING_TYPE_YARN = 2,
      LLAMA_ROPE_SCALING_TYPE_LONGROPE = 3,
      LLAMA_ROPE_SCALING_TYPE_MAX_VALUE = 3,
  };
  enum llama_pooling_type {
      LLAMA_POOLING_TYPE_UNSPECIFIED = -1,
      LLAMA_POOLING_TYPE_NONE = 0,
      LLAMA_POOLING_TYPE_MEAN = 1,
      LLAMA_POOLING_TYPE_CLS = 2,
      LLAMA_POOLING_TYPE_LAST = 3,
      LLAMA_POOLING_TYPE_RANK = 4,
  };
  enum llama_attention_type {
      LLAMA_ATTENTION_TYPE_UNSPECIFIED = -1,
      LLAMA_ATTENTION_TYPE_CAUSAL = 0,
      LLAMA_ATTENTION_TYPE_NON_CAUSAL = 1,
  };
  enum llama_flash_attn_type {
      LLAMA_FLASH_ATTN_TYPE_AUTO = -1,
      LLAMA_FLASH_ATTN_TYPE_DISABLED = 0,
      LLAMA_FLASH_ATTN_TYPE_ENABLED = 1,
  };
  enum llama_split_mode {
      LLAMA_SPLIT_MODE_NONE = 0,
      LLAMA_SPLIT_MODE_LAYER = 1,
      LLAMA_SPLIT_MODE_ROW = 2,
      LLAMA_SPLIT_MODE_TENSOR = 3,
  };
  enum llama_model_kv_override_type {
      LLAMA_KV_OVERRIDE_TYPE_INT = 0,
      LLAMA_KV_OVERRIDE_TYPE_FLOAT = 0,
      LLAMA_KV_OVERRIDE_TYPE_BOOL = 0,
      LLAMA_KV_OVERRIDE_TYPE_STR = 0,
  };
  enum llama_model_meta_key {
      LLAMA_MODEL_META_KEY_SAMPLING_SEQUENCE = 0,
      LLAMA_MODEL_META_KEY_SAMPLING_TOP_K = 0,
      LLAMA_MODEL_META_KEY_SAMPLING_TOP_P = 0,
      LLAMA_MODEL_META_KEY_SAMPLING_MIN_P = 0,
      LLAMA_MODEL_META_KEY_SAMPLING_XTC_PROBABILITY = 0,
      LLAMA_MODEL_META_KEY_SAMPLING_XTC_THRESHOLD = 0,
      LLAMA_MODEL_META_KEY_SAMPLING_TEMP = 0,
      LLAMA_MODEL_META_KEY_SAMPLING_PENALTY_LAST_N = 0,
      LLAMA_MODEL_META_KEY_SAMPLING_PENALTY_REPEAT = 0,
      LLAMA_MODEL_META_KEY_SAMPLING_MIROSTAT = 0,
      LLAMA_MODEL_META_KEY_SAMPLING_MIROSTAT_TAU = 0,
      LLAMA_MODEL_META_KEY_SAMPLING_MIROSTAT_ETA = 0,
  };

  -- Structs
  struct ggml_init_params {
      size_t mem_size;
      void * mem_buffer;
      bool no_alloc;
  };
  struct ggml_tensor {
      enum ggml_type type;
      struct ggml_backend_buffer * buffer;
      int64_t ne[4];
      size_t nb[4];
      enum ggml_op op;
      int32_t op_params[16];
      int32_t flags;
      struct ggml_tensor * src[10];
      struct ggml_tensor * view_src;
      size_t view_offs;
      void * data;
      char name[64];
      void * extra;
      char padding[8];
  };
  struct ggml_type_traits {
      const char * type_name;
      int64_t blck_size;
      int64_t blck_size_interleave;
      size_t type_size;
      bool is_quantized;
      ggml_to_float_t to_float;
      ggml_from_float_t from_float_ref;
  };
  struct ggml_threadpool_params {
      bool cpumask[512];
      int n_threads;
      enum ggml_sched_priority prio;
      uint32_t poll;
      bool strict_cpu;
      bool paused;
  };
  struct ggml_tallocr {
      ggml_backend_buffer_t buffer;
      void * base;
      size_t alignment;
      size_t offset;
  };
  struct ggml_backend_dev_caps {
      bool async;
      bool host_buffer;
      bool buffer_from_host_ptr;
      bool events;
  };
  struct ggml_backend_dev_props {
      const char * name;
      const char * description;
      size_t memory_free;
      size_t memory_total;
      enum ggml_backend_dev_type type;
      const char * device_id;
      struct ggml_backend_dev_caps caps;
  };
  struct ggml_backend_feature {
      const char * name;
      const char * value;
  };
  struct ggml_backend_meta_split_state {
      enum ggml_backend_meta_split_axis axis;
      int64_t ne[256];
      uint32_t n_segments;
  };
  struct ggml_backend_graph_copy {
      ggml_backend_buffer_t buffer;
      struct ggml_context * ctx_allocated;
      struct ggml_context * ctx_unallocated;
      struct ggml_cgraph * graph;
  };
  struct ggml_cplan {
      size_t work_size;
      uint8_t * work_data;
      int n_threads;
      struct ggml_threadpool * threadpool;
      ggml_abort_callback abort_callback;
      void * abort_callback_data;
      bool use_ref;
  };
  struct ggml_type_traits_cpu {
      ggml_from_float_t from_float;
      ggml_vec_dot_t vec_dot;
      enum ggml_type vec_dot_type;
      int64_t nrows;
  };
  struct ggml_opt_optimizer_params {
      struct (unnamed at scripts/../vendor/llama.cpp/ggml/include/ggml-opt.h:86:9) adamw;
      struct (unnamed at scripts/../vendor/llama.cpp/ggml/include/ggml-opt.h:93:9) sgd;
  };
  struct ggml_opt_params {
      ggml_backend_sched_t backend_sched;
      struct ggml_context * ctx_compute;
      struct ggml_tensor * inputs;
      struct ggml_tensor * outputs;
      enum ggml_opt_loss_type loss_type;
      enum ggml_opt_build_type build_type;
      int32_t opt_period;
      ggml_opt_get_optimizer_params get_opt_pars;
      void * get_opt_pars_ud;
      enum ggml_opt_optimizer_type optimizer;
  };
  struct gguf_init_params {
      bool no_alloc;
      struct ggml_context ** ctx;
  };
  struct llama_token_data {
      llama_token id;
      float logit;
      float p;
  };
  struct llama_token_data_array {
      llama_token_data * data;
      size_t size;
      int64_t selected;
      bool sorted;
  };
  struct llama_batch {
      int32_t n_tokens;
      llama_token * token;
      float * embd;
      llama_pos * pos;
      int32_t * n_seq_id;
      llama_seq_id ** seq_id;
      int8_t * logits;
  };
  struct llama_model_kv_override {
      enum llama_model_kv_override_type tag;
      char key[128];
      union llama_model_kv_override::(anonymous at scripts/../vendor/llama.cpp/include/llama.h:273:9) _unnamed;
  };
  struct llama_model_tensor_buft_override {
      const char * pattern;
      ggml_backend_buffer_type_t buft;
  };
  struct llama_model_params {
      ggml_backend_dev_t * devices;
      const struct llama_model_tensor_buft_override * tensor_buft_overrides;
      int32_t n_gpu_layers;
      enum llama_split_mode split_mode;
      int32_t main_gpu;
      const float * tensor_split;
      llama_progress_callback progress_callback;
      void * progress_callback_user_data;
      const struct llama_model_kv_override * kv_overrides;
      bool vocab_only;
      bool use_mmap;
      bool use_direct_io;
      bool use_mlock;
      bool check_tensors;
      bool use_extra_bufts;
      bool no_host;
      bool no_alloc;
  };
  struct llama_sampler_seq_config {
      llama_seq_id seq_id;
      struct llama_sampler * sampler;
  };
  struct llama_context_params {
      uint32_t n_ctx;
      uint32_t n_batch;
      uint32_t n_ubatch;
      uint32_t n_seq_max;
      int32_t n_threads;
      int32_t n_threads_batch;
      enum llama_rope_scaling_type rope_scaling_type;
      enum llama_pooling_type pooling_type;
      enum llama_attention_type attention_type;
      enum llama_flash_attn_type flash_attn_type;
      float rope_freq_base;
      float rope_freq_scale;
      float yarn_ext_factor;
      float yarn_attn_factor;
      float yarn_beta_fast;
      float yarn_beta_slow;
      uint32_t yarn_orig_ctx;
      float defrag_thold;
      ggml_backend_sched_eval_callback cb_eval;
      void * cb_eval_user_data;
      enum ggml_type type_k;
      enum ggml_type type_v;
      ggml_abort_callback abort_callback;
      void * abort_callback_data;
      bool embeddings;
      bool offload_kqv;
      bool no_perf;
      bool op_offload;
      bool swa_full;
      bool kv_unified;
      struct llama_sampler_seq_config * samplers;
      size_t n_samplers;
  };
  struct llama_model_tensor_override {
      const char * pattern;
      enum ggml_type type;
  };
  struct llama_model_imatrix_data {
      const char * name;
      const float * data;
      size_t size;
  };
  struct llama_model_quantize_params {
      int32_t nthread;
      enum llama_ftype ftype;
      enum ggml_type output_tensor_type;
      enum ggml_type token_embedding_type;
      bool allow_requantize;
      bool quantize_output_tensor;
      bool only_copy;
      bool pure;
      bool keep_split;
      bool dry_run;
      const struct llama_model_imatrix_data * imatrix;
      const struct llama_model_kv_override * kv_overrides;
      const struct llama_model_tensor_override * tt_overrides;
      const int32_t * prune_layers;
  };
  struct llama_logit_bias {
      llama_token token;
      float bias;
  };
  struct llama_sampler_chain_params {
      bool no_perf;
  };
  struct llama_chat_message {
      const char * role;
      const char * content;
  };
  struct llama_sampler_data {
      struct ggml_tensor * logits;
      struct ggml_tensor * probs;
      struct ggml_tensor * sampled;
      struct ggml_tensor * candidates;
  };
  struct llama_sampler_i {
      const char *(*)(const struct llama_sampler *) name;
      void (*)(struct llama_sampler *, llama_token) accept;
      void (*)(struct llama_sampler *, llama_token_data_array *) apply;
      void (*)(struct llama_sampler *) reset;
      struct llama_sampler *(*)(const struct llama_sampler *) clone;
      void (*)(struct llama_sampler *) free;
      bool (*)(struct llama_sampler *, ggml_backend_buffer_type_t) backend_init;
      void (*)(struct llama_sampler *, struct ggml_context *, struct ggml_cgraph *, struct ggml_tensor *) backend_accept;
      void (*)(struct llama_sampler *, struct ggml_context *, struct ggml_cgraph *, struct llama_sampler_data *) backend_apply;
      void (*)(struct llama_sampler *) backend_set_input;
  };
  struct llama_sampler {
      struct llama_sampler_i * iface;
      llama_sampler_context_t ctx;
  };
  struct llama_perf_context_data {
      double t_start_ms;
      double t_load_ms;
      double t_p_eval_ms;
      double t_eval_ms;
      int32_t n_p_eval;
      int32_t n_eval;
      int32_t n_reused;
  };
  struct llama_perf_sampler_data {
      double t_sample_ms;
      int32_t n_sample;
  };
  struct llama_opt_params {
      uint32_t n_ctx_train;
      llama_opt_param_filter param_filter;
      void * param_filter_ud;
      ggml_opt_get_optimizer_params get_opt_pars;
      void * get_opt_pars_ud;
      enum ggml_opt_optimizer_type optimizer_type;
  };

  -- Typedefs
  typedef void (*)(const char *) ggml_abort_callback_t;
  typedef uint16_t ggml_fp16_t;
  typedef struct ggml_bf16_t ggml_bf16_t;
  typedef bool (*)(void *) ggml_abort_callback;
  typedef uint8_t[16] ggml_guid;
  typedef ggml_guid * ggml_guid_t;
  typedef void (*)(struct ggml_tensor *, const struct ggml_tensor *, int, int, void *) ggml_custom1_op_t;
  typedef void (*)(struct ggml_tensor *, const struct ggml_tensor *, const struct ggml_tensor *, int, int, void *) ggml_custom2_op_t;
  typedef void (*)(struct ggml_tensor *, const struct ggml_tensor *, const struct ggml_tensor *, const struct ggml_tensor *, int, int, void *) ggml_custom3_op_t;
  typedef void (*)(struct ggml_tensor *, int, int, void *) ggml_custom_op_t;
  typedef void (*)(enum ggml_log_level, const char *, void *) ggml_log_callback;
  typedef void (*)(const void *restrict, float *restrict, int64_t) ggml_to_float_t;
  typedef void (*)(const float *restrict, void *restrict, int64_t) ggml_from_float_t;
  typedef struct ggml_threadpool * ggml_threadpool_t;
  typedef struct ggml_backend_buffer_type * ggml_backend_buffer_type_t;
  typedef struct ggml_backend_buffer * ggml_backend_buffer_t;
  typedef struct ggml_backend * ggml_backend_t;
  typedef struct ggml_gallocr * ggml_gallocr_t;
  typedef struct ggml_backend_event * ggml_backend_event_t;
  typedef void * ggml_backend_graph_plan_t;
  typedef struct ggml_backend_reg * ggml_backend_reg_t;
  typedef struct ggml_backend_device * ggml_backend_dev_t;
  typedef void *(*)(ggml_backend_t *, size_t) ggml_backend_comm_init_t;
  typedef void (*)(void *) ggml_backend_comm_free_t;
  typedef bool (*)(void *, struct ggml_tensor **) ggml_backend_comm_allreduce_tensor_t;
  typedef ggml_backend_buffer_type_t (*)(int, const float *) ggml_backend_split_buffer_type_t;
  typedef void (*)(ggml_backend_t, int) ggml_backend_set_n_threads_t;
  typedef ggml_backend_buffer_type_t *(*)(ggml_backend_dev_t) ggml_backend_dev_get_extra_bufts_t;
  typedef void (*)(ggml_backend_t, ggml_abort_callback, void *) ggml_backend_set_abort_callback_t;
  typedef struct ggml_backend_feature *(*)(ggml_backend_reg_t) ggml_backend_get_features_t;
  typedef struct ggml_backend_sched * ggml_backend_sched_t;
  typedef bool (*)(struct ggml_tensor *, bool, void *) ggml_backend_sched_eval_callback;
  typedef struct ggml_backend_meta_split_state (*)(const struct ggml_tensor *, void *) ggml_backend_meta_get_split_state_t;
  typedef bool (*)(int, struct ggml_tensor *, struct ggml_tensor *, void *) ggml_backend_eval_callback;
  typedef void (*)(int, float *restrict, size_t, const void *restrict, size_t, const void *restrict, size_t, int) ggml_vec_dot_t;
  typedef struct ggml_opt_dataset * ggml_opt_dataset_t;
  typedef struct ggml_opt_context * ggml_opt_context_t;
  typedef struct ggml_opt_result * ggml_opt_result_t;
  typedef struct ggml_opt_optimizer_params (*)(void *) ggml_opt_get_optimizer_params;
  typedef void (*)(bool, ggml_opt_context_t, ggml_opt_dataset_t, ggml_opt_result_t, int64_t, int64_t, int64_t) ggml_opt_epoch_callback;
  typedef struct llama_memory_i * llama_memory_t;
  typedef int32_t llama_pos;
  typedef int32_t llama_token;
  typedef int32_t llama_seq_id;
  typedef struct llama_token_data llama_token_data;
  typedef struct llama_token_data_array llama_token_data_array;
  typedef bool (*)(float, void *) llama_progress_callback;
  typedef struct llama_batch llama_batch;
  typedef struct llama_model_quantize_params llama_model_quantize_params;
  typedef struct llama_logit_bias llama_logit_bias;
  typedef struct llama_sampler_chain_params llama_sampler_chain_params;
  typedef struct llama_chat_message llama_chat_message;
  typedef void (*)(struct ggml_tensor *, void *) llama_model_set_tensor_data_t;
  typedef uint32_t llama_state_seq_flags;
  typedef void * llama_sampler_context_t;
  typedef bool (*)(const struct ggml_tensor *, void *) llama_opt_param_filter;
]]

-- types.lua does NOT load any native lib — it only declares.
-- See loader.lua for the actual ffi.load calls.
return true
