--- @module ffi_gen.clang
--- @author  ion7 / generate_ffi.lua
---
--- Wraps the `clang` compiler driver to produce a JSON dump of a translation
--- unit's AST and decode it into a Lua table.

local util = require "ffi_gen.util"
local json = require "ion7.vendor.json"

local string_format = string.format
local table_concat  = table.concat
local table_insert  = table.insert
local os_execute    = os.execute
local os_remove     = os.remove

local M = {}

-- ── Locating the clang executable ──────────────────────────────────────────

--- Find an executable `clang` on the host. Resolution order:
---   1. Explicit override passed by caller.
---   2. `ION7_CLANG` environment variable.
---   3. Default Windows install at `C:/Program Files/LLVM/bin/clang.exe`
---      (we use the 8.3 short path `Progra~1` to dodge the cmd.exe quoting
---      pain caused by the embedded space).
---   4. Plain `clang` on the PATH.
---
--- @param  explicit_path string|nil Path provided by caller (e.g. CLI flag).
--- @return string                   Resolved executable path or basename.
function M.find_clang(explicit_path)
  if explicit_path and explicit_path ~= "" then return explicit_path end
  local env = os.getenv("ION7_CLANG")
  if env and env ~= "" then return env end
  if util.IS_WINDOWS and util.file_exists("C:/Progra~1/LLVM/bin/clang.exe") then
    return "C:/Progra~1/LLVM/bin/clang.exe"
  end
  return "clang"
end

-- ── Combined header construction ───────────────────────────────────────────

--- Build a temporary `.h` file that `#include`s every requested header by
--- BASENAME, relying on the `-I` directories passed to clang to resolve them.
---
--- We deliberately use the basename rather than the full path because the
--- combined `.h` lives in the system temp dir, so relative paths inside it
--- would not resolve correctly (clang interprets `#include "foo"` paths
--- relative to the including file, not to the original CWD).
---
--- The include order matches `headers`; this matters because some headers
--- (particularly `llama.h`) re-declare types from headers they include and
--- we want clang to settle on the canonical declaration that appears first.
---
--- @param  headers string[] Absolute or relative header paths (only basenames are used).
--- @return string           Path to the freshly-written combined header.
function M.build_combined_header(headers)
  local path = util.tmp_path("_combined.h")
  local lines, n = {}, 0
  local function push(s) n = n + 1; lines[n] = s end

  push("/* AUTO-GENERATED by generate_ffi.lua — combined header for one-shot")
  push(" * clang AST dump. Safe to delete; this file is rewritten on every run. */")
  push("")
  for _, h in ipairs(headers) do
    push(string_format('#include "%s"', util.basename(h)))
  end
  push("")
  util.write_file(path, table_concat(lines, "\n"))
  return path
end

-- ── Spawning clang ─────────────────────────────────────────────────────────

--- Build the full clang command line for an AST dump invocation.
---
--- @param  clang_path     string   Path to the clang executable.
--- @param  source_path    string   Source file to parse (typically the combined `.h`).
--- @param  include_paths  string[] List of `-I` include directories.
--- @param  defines        string[] Extra `-D` flags (already including the `-D` prefix).
--- @param  out_path       string   Path to redirect stdout (the JSON dump) to.
--- @param  err_path       string   Path to redirect stderr (warnings/errors) to.
--- @return string                  Shell command, ready for `os.execute`.
local function build_clang_cmd(clang_path, source_path, include_paths, defines, out_path, err_path)
  local parts, n = {}, 0
  local function push(s) n = n + 1; parts[n] = s end

  push('"' .. clang_path .. '"')
  push("-Xclang"); push("-ast-dump=json")
  push("-fsyntax-only")
  push("-x"); push("c")
  push("-std=c11")
  push("-Wno-macro-redefined")
  for _, def in ipairs(defines) do push('"' .. def .. '"') end
  for _, inc in ipairs(include_paths) do
    push('-I"' .. util.normalize_path(inc) .. '"')
  end
  push('"' .. util.normalize_path(source_path) .. '"')
  push('> "' .. out_path .. '"')
  push('2> "' .. err_path .. '"')

  return util.wrap_for_shell(table_concat(parts, " "))
end

--- Spawn clang to dump the AST of `source_path` and return the decoded JSON
--- root as a Lua table. The temporary stdout/stderr files are removed on
--- success and on failure.
---
--- @param  clang_path    string   Path to the clang executable.
--- @param  source_path   string   Source file to parse (combined `.h` recommended).
--- @param  include_paths string[] List of `-I` include directories.
--- @param  defines       string[] Extra `-D` flags (must include the `-D` prefix).
--- @return table|nil ast Decoded AST root (`TranslationUnitDecl`), or nil on failure.
--- @return string|nil err Error message if parsing failed.
function M.dump_ast(clang_path, source_path, include_paths, defines)
  local out_path = util.tmp_path(".json")
  local err_path = util.tmp_path(".err")
  local cmd = build_clang_cmd(clang_path, source_path, include_paths, defines,
                              out_path, err_path)
  local rc = os_execute(cmd)
  if not util.exec_ok(rc) then
    local err = util.read_file(err_path) or "(no stderr captured)"
    os_remove(out_path); os_remove(err_path)
    return nil, "clang failed:\n" .. err
  end

  local raw, rerr = util.read_file(out_path)
  os_remove(out_path); os_remove(err_path)
  if not raw then
    return nil, "could not read clang stdout: " .. tostring(rerr)
  end

  local ok, ast = pcall(json.decode, raw)
  if not ok then
    return nil, "JSON decode failed: " .. tostring(ast)
  end
  return ast, nil
end

return M
