--- @module ffi_gen.emit
--- @author  ion7 / generate_ffi.lua
---
--- Lua source emission. Takes the flat list of `Decl` records produced by
--- `ffi_gen.ast` and writes the per-file `ffi.cdef` blocks plus the `loader`
--- module that resolves the native shared libraries at runtime.
---
--- File layout (under `<project>/src/ion7/core/ffi/`):
---   types.lua            - all forward decls, enums, structs and typedefs.
---   loader.lua           - `ffi.load` wrappers for libllama / libggml.
---   llama/<group>.lua    - one file per `LLAMA_GROUPS` bucket.
---   ggml/<group>.lua     - one file per `GGML_GROUPS` bucket.
---   gguf/<group>.lua     - one file per `GGUF_GROUPS` bucket.

local util = require "ffi_gen.util"

local string_format = string.format
local table_concat  = table.concat
local table_sort    = table.sort

local M = {}

-- ── Lua header template ────────────────────────────────────────────────────

-- The template embeds two `[[` and two `]]` literally (one pair belongs to
-- our framing, one pair to the inner `ffi.cdef[[ ... ]]`). Lua 5.1 long
-- strings cannot nest brackets of the same level, so we use `[==[ ... ]==]`
-- to bypass that.
local LUA_HEADER_FMT = [==[-- src/ion7/core/ffi/%s
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: %s

local ffi = require "ffi"
%s
ffi.cdef[[
%s
]]
%s
]==]

--- Render a single Lua FFI file from its components.
---
--- @param  rel_path           string Path under `src/ion7/core/ffi/` (used in the comment header).
--- @param  sources            string Comma-separated list of source headers (header comment).
--- @param  require_types_line string Either `""` (for types.lua) or a `require "ion7.core.ffi.types"` line.
--- @param  cdef_body          string The body inside `ffi.cdef[[ ... ]]`, already indented.
--- @param  return_lib         string Tail of the file (`return loader.<ns>` or `return true`).
--- @return string                    Complete Lua source ready to write.
local function render_lua_file(rel_path, sources, require_types_line, cdef_body, return_lib)
  return string_format(LUA_HEADER_FMT, rel_path, sources, require_types_line, cdef_body, return_lib)
end

-- ── Dedup helpers ──────────────────────────────────────────────────────────

--- Return a new array with duplicate entries (by `.name`) removed. The first
--- occurrence wins and the relative order is preserved.
---
--- @generic D : { name: string }
--- @param   decls D[]
--- @return  D[]
local function unique_by_name(decls)
  local out, seen, n = {}, {}, 0
  for i = 1, #decls do
    local d = decls[i]
    if not seen[d.name] then
      seen[d.name] = true
      n = n + 1
      out[n] = d
    end
  end
  return out
end

-- ── types.lua ──────────────────────────────────────────────────────────────

--- Emit `types.lua`: the consolidated forward declarations, enums, structs,
--- and typedefs.
---
--- A struct that exists in both `struct_fwd` and `struct` form is kept only
--- as the complete struct (the forward declaration is dropped, since the
--- complete one supersedes it for FFI purposes).
---
--- @param  decls      ffi_gen.ast.Decl[] All non-function decls collected during the walk.
--- @param  output_dir string             Absolute path to `src/ion7/core/ffi/`.
function M.write_types(decls, output_dir)
  local fwds, structs, typedefs, enums = {}, {}, {}, {}
  local nf, ns, nt, ne = 0, 0, 0, 0
  for i = 1, #decls do
    local d = decls[i]
    local k = d.kind
    if     k == "struct_fwd" then nf = nf + 1; fwds[nf]     = d
    elseif k == "struct"     then ns = ns + 1; structs[ns]  = d
    elseif k == "typedef"    then nt = nt + 1; typedefs[nt] = d
    elseif k == "enum"       then ne = ne + 1; enums[ne]    = d
    end
  end

  structs  = unique_by_name(structs)
  typedefs = unique_by_name(typedefs)
  enums    = unique_by_name(enums)

  -- Forward decls only kept for structs that have no complete definition.
  local struct_names = {}
  for i = 1, #structs do struct_names[structs[i].name] = true end
  local fwds_kept, fk_n, seen_fwd = {}, 0, {}
  for i = 1, #fwds do
    local d = fwds[i]
    if not struct_names[d.name] and not seen_fwd[d.name] then
      seen_fwd[d.name] = true
      fk_n = fk_n + 1
      fwds_kept[fk_n] = d
    end
  end

  local function block(label, items)
    if #items == 0 then return nil end
    local body, bn = {}, 0
    for i = 1, #items do bn = bn + 1; body[bn] = items[i].spelling end
    return "-- " .. label .. "\n" .. table_concat(body, "\n")
  end

  local blocks, bn = {}, 0
  local function add(label, items)
    local b = block(label, items)
    if b then bn = bn + 1; blocks[bn] = b end
  end
  add("Forward declarations", fwds_kept)
  add("Enums",                enums)
  add("Structs",              structs)
  add("Typedefs",             typedefs)
  local cdef_body = table_concat(blocks, "\n\n")

  local out = render_lua_file(
    "types.lua",
    "llama.h, ggml.h and the public ggml-* headers",
    "",
    util.indent(cdef_body, "  "),
    "\n-- types.lua does NOT load any native lib — it only declares.\n"
    .. "-- See loader.lua for the actual ffi.load calls.\nreturn true"
  )
  util.write_file(output_dir .. "/types.lua", out)
end

-- ── per-group files ────────────────────────────────────────────────────────

--- Emit `<parent>/<group>.lua` containing the function declarations for that
--- bucket. Functions are sorted by source line for stable diffs across runs.
---
--- @param  group_name string             Bucket name (e.g. `"context"`, `"sampler"`).
--- @param  fns        ffi_gen.ast.Decl[] Function decls for this bucket.
--- @param  parent     "llama"|"ggml"|"gguf" Top-level namespace.
--- @param  output_dir string             Absolute path to `src/ion7/core/ffi/`.
function M.write_group(group_name, fns, parent, output_dir)
  if #fns == 0 then return end

  table_sort(fns, function(a, b) return a.extent_start < b.extent_start end)

  local body, n = {}, 0
  local source_set = {}
  for i = 1, #fns do
    local f = fns[i]
    n = n + 1
    body[n] = f.spelling
    source_set[util.basename(f.source_file)] = true
  end
  local sources = util.sorted_keys(source_set)

  local out = render_lua_file(
    parent .. "/" .. group_name .. ".lua",
    table_concat(sources, ", "),
    'require "ion7.core.ffi.types"   -- ensure types are declared first\n',
    util.indent(table_concat(body, "\n"), "  "),
    'local loader = require "ion7.core.ffi.loader"\nreturn loader.' .. parent
  )
  local target_dir = output_dir .. "/" .. parent
  util.mkdir_p(target_dir)
  util.write_file(target_dir .. "/" .. group_name .. ".lua", out)
end

-- ── loader.lua ─────────────────────────────────────────────────────────────

-- Loader body split into prefix + suffix around the variable lines. We avoid
-- string.format here because the inner _try_load code itself uses `%s` for its
-- runtime error messages, which would clash with format placeholders.
local LOADER_PREFIX = [[-- src/ion7/core/ffi/loader.lua
-- Loads the native shared libs (libllama, libggml) and exposes their handles.
-- Resolution order: ION7_LIBLLAMA_PATH > vendor/llama.cpp/build/ > system.

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are ready

local function _try_load(name, candidates)
  for _, path in ipairs(candidates) do
    if path then
      local ok, lib = pcall(function() return ffi.load(path) end)
      if ok then return lib end
    end
  end
  error(string.format("[ion7-core] %s not found. Candidates: %s",
    name, table.concat(candidates, " | ")))
end

local function _candidates(env_var, base_name)
  return {
    os.getenv(env_var),
    "vendor/llama.cpp/build/lib/lib" .. base_name .. ".so",
    "vendor/llama.cpp/build/" .. base_name .. ".dll",
    "/usr/local/lib/lib" .. base_name .. ".so",
    "lib" .. base_name .. ".so",
  }
end

local M = {}

M.llama = _try_load("libllama", _candidates("ION7_LIBLLAMA_PATH", "llama"))
]]

local LOADER_SUFFIX = [[
return M
]]

--- Emit `loader.lua`. The body is mostly fixed; we only conditionally include
--- the optional ggml line and the Vulkan-specific note.
---
--- @param  output_dir string  Absolute path to `src/ion7/core/ffi/`.
--- @param  has_ggml   boolean Whether to load `libggml`.
--- @param  has_vulkan boolean Whether to mention the optional Vulkan-specific lib.
function M.write_loader(output_dir, has_ggml, has_vulkan)
  local ggml_line = has_ggml
    and 'M.ggml  = _try_load("libggml",  _candidates("ION7_LIBGGML_PATH",  "ggml"))\n'
    or  ""
  local vulkan_note = has_vulkan
    and "-- libggml-vulkan is usually statically linked into libggml — uncomment if not:\n"
        .. "-- M.ggml_vulkan = _try_load(\"libggml-vulkan\", _candidates(\"ION7_LIBGGML_VULKAN_PATH\", \"ggml-vulkan\"))\n"
    or  ""
  local body = LOADER_PREFIX .. ggml_line .. vulkan_note .. LOADER_SUFFIX
  util.write_file(output_dir .. "/loader.lua", body)
end

return M
