--- @module ffi_gen.emit
--- @author  ion7 / generate_ffi.lua
---
--- Lua source emission. Takes the flat list of `Decl` records produced by
--- `ffi_gen.ast` and writes the per-file `ffi.cdef` blocks plus the `loader`
--- module that resolves the native shared libraries at runtime.
---
--- File layout (under `<project>/src/ion7/core/ffi/`):
---   types.lua            - all forward decls, enums, structs and typedefs.
---   loader.lua           - `ffi.load` wrappers for libllama / libggml.
---   llama/<group>.lua    - one file per `LLAMA_GROUPS` bucket.
---   ggml/<group>.lua     - one file per `GGML_GROUPS` bucket.
---   gguf/<group>.lua     - one file per `GGUF_GROUPS` bucket.

local util = require "ffi_gen.util"

local string_format = string.format
local table_concat  = table.concat
local table_sort    = table.sort

local M = {}

-- ── Lua header template ────────────────────────────────────────────────────

-- The template embeds two `[[` and two `]]` literally (one pair belongs to
-- our framing, one pair to the inner `ffi.cdef[[ ... ]]`). Lua 5.1 long
-- strings cannot nest brackets of the same level, so we use `[==[ ... ]==]`
-- to bypass that.
local LUA_HEADER_FMT = [==[-- src/ion7/core/ffi/%s
-- AUTO-GENERATED by scripts/generate_ffi.lua — do not edit by hand.
-- Regenerate after a llama.cpp bump: luajit scripts/generate_ffi.lua
-- Source: %s

local ffi = require "ffi"
%s
ffi.cdef[[
%s
]]
%s
]==]

--- Render a single Lua FFI file from its components.
---
--- @param  rel_path           string Path under `src/ion7/core/ffi/` (used in the comment header).
--- @param  sources            string Comma-separated list of source headers (header comment).
--- @param  require_types_line string Either `""` (for types.lua) or a `require "ion7.core.ffi.types"` line.
--- @param  cdef_body          string The body inside `ffi.cdef[[ ... ]]`, already indented.
--- @param  return_lib         string Tail of the file (`return loader.<ns>` or `return true`).
--- @return string                    Complete Lua source ready to write.
local function render_lua_file(rel_path, sources, require_types_line, cdef_body, return_lib)
  return string_format(LUA_HEADER_FMT, rel_path, sources, require_types_line, cdef_body, return_lib)
end

-- ── Dedup helpers ──────────────────────────────────────────────────────────

--- Return a new array with duplicate entries (by `.name`) removed. The first
--- occurrence wins and the relative order is preserved.
---
--- @generic D : { name: string }
--- @param   decls D[]
--- @return  D[]
local function unique_by_name(decls)
  local out, seen, n = {}, {}, 0
  for i = 1, #decls do
    local d = decls[i]
    if not seen[d.name] then
      seen[d.name] = true
      n = n + 1
      out[n] = d
    end
  end
  return out
end

-- ── types.lua ──────────────────────────────────────────────────────────────

--- Emit `types.lua` : the consolidated forward declarations, enums,
--- structs and typedefs.
---
--- Emission strategy :
---
---   1. Forward declarations FIRST (only those whose name has no complete
---      `struct` definition collected later — otherwise the forward is
---      redundant and clutters the output).
---
---   2. All other decls (`struct`, `typedef`, `enum`) IN AST INSERTION
---      ORDER. clang walks the translation unit in dependency-correct
---      order (a struct field referencing a typedef sees that typedef
---      already in scope), so we just preserve the order our `walk_ast`
---      observed.
---
---      DO NOT sort by `(source_file, extent_start)` here: filename
---      lexicographic order can violate dependency order — for instance,
---      `ggml-backend.h` sorts BEFORE `ggml.h` (`-` < `.` in ASCII),
---      whereas the actual include chain pulls `ggml.h` first.
---
--- Decls are deduplicated by name with first-seen wins, which preserves
--- the canonical (earliest) declaration. Lua `--` comments are forbidden
--- inside the cdef body since it must be valid C; section labels use
--- `/* ... */`.
---
--- @param  decls      ffi_gen.ast.Decl[] All non-function decls collected during the walk.
--- @param  output_dir string             Absolute path to `src/ion7/core/ffi/`.
function M.write_types(decls, output_dir)
  -- Split into (forwards) vs (everything else), keeping insertion order.
  local fwds_raw, rest = {}, {}
  local nf, nr = 0, 0
  for i = 1, #decls do
    local d = decls[i]
    if d.kind == "struct_fwd" then nf = nf + 1; fwds_raw[nf] = d
    else                            nr = nr + 1; rest[nr]    = d
    end
  end

  -- Dedup `rest` by name, first-seen wins. `unique_by_name` preserves
  -- the original insertion order, which is what we want.
  local rest_unique = unique_by_name(rest)

  -- Build the set of struct names that have a complete definition; these
  -- supersede any forward declaration with the same name.
  local has_full_struct = {}
  for i = 1, #rest_unique do
    local d = rest_unique[i]
    if d.kind == "struct" then has_full_struct[d.name] = true end
  end

  -- Keep only forwards that fill a real gap (no full struct shows up later).
  local fwds_kept, fk_n, seen_fwd = {}, 0, {}
  for i = 1, #fwds_raw do
    local d = fwds_raw[i]
    if not has_full_struct[d.name] and not seen_fwd[d.name] then
      seen_fwd[d.name] = true
      fk_n = fk_n + 1
      fwds_kept[fk_n] = d
    end
  end

  -- Render. C-style comments only — the body lives inside ffi.cdef[[...]].
  local function block(label, items)
    if #items == 0 then return nil end
    local body, bn = {}, 0
    for i = 1, #items do bn = bn + 1; body[bn] = items[i].spelling end
    return "/* " .. label .. " */\n" .. table_concat(body, "\n")
  end

  local blocks, bn = {}, 0
  local function add(label, items)
    local b = block(label, items)
    if b then bn = bn + 1; blocks[bn] = b end
  end

  -- Preamble : opaque system types referenced by some headers but never
  -- defined in their AST (they come from <stdio.h>, <time.h>, ...). The
  -- LuaJIT FFI parser does not pull in libc, so we forward-declare them
  -- as opaque structs. Pointer-only usage (the only kind we encounter)
  -- works fine; dereferencing them from Lua would have failed anyway.
  bn = bn + 1
  blocks[bn] = "/* Opaque system types (libc forwards) */\ntypedef struct __ion7_FILE FILE;"

  add("Forward declarations",      fwds_kept)
  add("Definitions (source order)", rest_unique)
  local cdef_body = table_concat(blocks, "\n\n")

  local out = render_lua_file(
    "types.lua",
    "llama.h, ggml.h and the public ggml-* headers",
    "",
    util.indent(cdef_body, "  "),
    "\n-- types.lua does NOT load any native lib — it only declares.\n"
    .. "-- See loader.lua for the actual ffi.load calls.\nreturn true"
  )
  util.write_file(output_dir .. "/types.lua", out)
end

-- ── per-group files ────────────────────────────────────────────────────────

--- Emit `<parent>/<group>.lua` containing the function declarations for that
--- bucket. Functions are sorted by source line for stable diffs across runs.
---
--- @param  group_name string             Bucket name (e.g. `"context"`, `"sampler"`).
--- @param  fns        ffi_gen.ast.Decl[] Function decls for this bucket.
--- @param  parent     "llama"|"ggml"|"gguf" Top-level namespace.
--- @param  output_dir string             Absolute path to `src/ion7/core/ffi/`.
function M.write_group(group_name, fns, parent, output_dir)
  if #fns == 0 then return end

  table_sort(fns, function(a, b) return a.extent_start < b.extent_start end)

  local body, n = {}, 0
  local source_set = {}
  for i = 1, #fns do
    local f = fns[i]
    n = n + 1
    body[n] = f.spelling
    source_set[util.basename(f.source_file)] = true
  end
  local sources = util.sorted_keys(source_set)

  local out = render_lua_file(
    parent .. "/" .. group_name .. ".lua",
    table_concat(sources, ", "),
    'require "ion7.core.ffi.types"   -- ensure types are declared first\n',
    util.indent(table_concat(body, "\n"), "  "),
    'local loader = require "ion7.core.ffi.loader"\nreturn loader.' .. parent
  )
  local target_dir = output_dir .. "/" .. parent
  util.mkdir_p(target_dir)
  util.write_file(target_dir .. "/" .. group_name .. ".lua", out)
end

-- ── loader.lua ─────────────────────────────────────────────────────────────

-- Loader body split into prefix + suffix around the variable lines. We avoid
-- string.format here because the inner _try_load code itself uses `%s` for its
-- runtime error messages, which would clash with format placeholders.
local LOADER_PREFIX = [[-- src/ion7/core/ffi/loader.lua
-- Loads the native shared libs (libllama, libggml) and exposes their handles.
-- Resolution order: ION7_LIBLLAMA_PATH > vendor/llama.cpp/build/ > system.

local ffi = require "ffi"
require "ion7.core.ffi.types"   -- ensure types are ready

-- Filter nil candidates (env vars not set) up front : `ipairs` would stop
-- at the first nil and `table.concat` in the error message would crash on
-- a sparse table.
local function _try_load(name, candidates)
  local clean, n = {}, 0
  for _, p in pairs(candidates) do
    if p and p ~= "" then n = n + 1; clean[n] = p end
  end
  for _, path in ipairs(clean) do
    local ok, lib = pcall(function() return ffi.load(path) end)
    if ok then return lib end
  end
  error(string.format("[ion7-core] %s not found. Candidates: %s",
    name, table.concat(clean, " | ")))
end

local function _candidates(env_var, base_name)
  return {
    os.getenv(env_var),
    "vendor/llama.cpp/build/lib/lib" .. base_name .. ".so",
    "vendor/llama.cpp/build/" .. base_name .. ".dll",
    "/usr/local/lib/lib" .. base_name .. ".so",
    "lib" .. base_name .. ".so",
  }
end

local M = {}

M.llama = _try_load("libllama", _candidates("ION7_LIBLLAMA_PATH", "llama"))
]]

local LOADER_SUFFIX = [[
return M
]]

--- Emit `loader.lua`. The body is mostly fixed; we only conditionally include
--- the optional ggml line and the Vulkan-specific note.
---
--- @param  output_dir string  Absolute path to `src/ion7/core/ffi/`.
--- @param  has_ggml   boolean Whether to load `libggml`.
--- @param  has_vulkan boolean Whether to mention the optional Vulkan-specific lib.
function M.write_loader(output_dir, has_ggml, has_vulkan)
  local ggml_line = has_ggml
    and 'M.ggml  = _try_load("libggml",  _candidates("ION7_LIBGGML_PATH",  "ggml"))\n'
    or  ""
  local vulkan_note = has_vulkan
    and "-- libggml-vulkan is usually statically linked into libggml — uncomment if not:\n"
        .. "-- M.ggml_vulkan = _try_load(\"libggml-vulkan\", _candidates(\"ION7_LIBGGML_VULKAN_PATH\", \"ggml-vulkan\"))\n"
    or  ""
  local body = LOADER_PREFIX .. ggml_line .. vulkan_note .. LOADER_SUFFIX
  util.write_file(output_dir .. "/loader.lua", body)
end

return M
